### ISSUE TITLE
avoid/prefer by Uid

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#101]
What about adding --avoid/prefer by Uid?
This may be relevant for servers.
For example,  --avoid-by-uid 33

**Comment by rfjakob** [comment]
Not sure about this - I believe you can set `oom_score_adj` through the .service file of the server: https://www.freedesktop.org/software/systemd/man/systemd.exec.html#OOMScoreAdjust=

**Comment by rfjakob** [comment]
(earlyoom will respect oom_score_adj unless you pass `-i`)

**Comment by hakavlad** [comment]
What about add this to systemd unit:
```
ProtectSystem=strict
```
' It is recommended to enable this setting for all long-running services, unless they are involved with system updates or need to modify the operating system in other ways.'

**Comment by hakavlad** [comment]
> you can set oom_score_adj through the .service

Gentoo with openrc and Devuan is not use  .service file, for example.

**Comment by hakavlad** [comment]
Also what about re matching with cmdline?

**Comment by rfjakob** [comment]
Well, Gentoo and Devuan should do it through their init system of choice.

Regex cmdline seems like a good idea, though.

**Comment by hakavlad** [comment]
>Regex cmdline seems like a good idea, though.

Do you plan to implenent it?
When will you do this?

**Comment by rfjakob** [comment]
Yes, in january maybe
