### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#102]
I've noticed you don't have a CoC yet. Care to accept one? I would suggest accepting [NCoC](https://github.com/domgetter/NCoC/blob/master/CODE_OF_CONDUCT.md) CoC, believe me it's an incredible CoC, everyone should accept it or at least try it. You would be amazed how great of a CoC it is.

Here is how you can accept a CoC: https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

Please do, okay?

**Comment by rfjakob** [comment]
Haha, no, the NCoC seems to be missing the "don't be an asshole" part that I find pretty important

**Comment by Koopiq** [comment]
>don't be an asshole

Then may I suggest ContributorCovenant's coc instead? It doesn't have your exact wording concerning assholes, but it does have "don't be an asshole" vibe overall and it's just a great coc.

It's dangerous to live without a coc these days. You should accept one.

**Comment by hakavlad** [comment]
>It's dangerous to live without a coc

Why?

**Comment by Koopiq** [comment]
Without a coc you can accidentally hurt someone's feelings and not even notice it. Having a coc is essential to building a safe space.

**Comment by rfjakob** [comment]
Indeed the contributor covenant coc looks pretty good to me. And the [list of adopters](https://www.contributor-covenant.org/adopters) is impressive - the linux kernel has [added it](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8a104f8b5867c682d994ffa7a74093c54469c11f) in september.

**Comment by hakavlad** [comment]
>dangerous to live without a coc

>hurt someone's feelings

>building a safe space

SJW bingo!

**Comment by Koopiq** [comment]
Any progress on this matter? It is quite important.

**Comment by rfjakob** [comment]
Added the contributor covenant coc and linked it in the changelog, thanks
