### ISSUE TITLE
Stop fork bombs

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#109]
What about add anti fork bomb functions in earlyoom? Like in this https://github.com/hakavlad/fork-bomb-killer program.

**Comment by rfjakob** [comment]
> A daemon for Linux that detects and safely neutralises simple fork bombs.

Will this kill make when compiling a big application?

**Comment by hakavlad** [comment]
It depends on the settings.

**Comment by rfjakob** [comment]
Too risky, sorry, will not add to earlyoom.

**Comment by hakavlad** [comment]
The option can be disabled by default.
