### ISSUE TITLE
main.c:247:45: error: ‘MCL_ONFAULT’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by barissimsek** [rfjakob/earlyoom#113]
Hi.

I couldn't compile the source due to below error:

make
cc  -Wall -Wextra -DVERSION=\"v1.2-25-g319e959\" -g -fstack-protector-all -std=gnu99 -o earlyoom meminfo.c kill.c msg.c main.c sanitize.c
msg.c: In function ‘parse_term_kill_tuple’:
msg.c:53:5: warning: missing braces around initializer [-Wmissing-braces]
     term_kill_tuple_t tuple = { 0 };
     ^
msg.c:53:5: warning: (near initialization for ‘tuple.err’) [-Wmissing-braces]
msg.c:53:5: warning: missing initializer for field ‘term’ of ‘term_kill_tuple_t’ [-Wmissing-field-initializers]
In file included from msg.c:10:0:
msg.h:14:10: note: ‘term’ declared here
     long term;
          ^
main.c: In function ‘main’:
main.c:247:45: error: ‘MCL_ONFAULT’ undeclared (first use in this function)
     if (mlockall(MCL_CURRENT | MCL_FUTURE | MCL_ONFAULT) != 0) {
                                             ^
main.c:247:45: note: each undeclared identifier is reported only once for each function it appears in
make: *** [earlyoom] Error 1

OS:
Centos 7.6 with elrepo 4.x kernel
uname -r
4.16.7-1.el7.elrepo.x86_64

gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)

**Comment by rfjakob** [comment]
Interesting case, thanks for the report. Your kernel is recent enough to support MCL_ONFAULT, but your glibc is too old to define it.

Fixed via 7cdb65c4ba608c8e8cbf40ef17b832d2ec7fbac2, thanks!

**Comment by barissimsek** [comment]
Redhat and Centos is too conservative about gcc unfortunately. Thanks for the fix.
