### ISSUE TITLE
Suggestion: change default reporting interval

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [rfjakob/earlyoom#116]
I know - having discovered just now - that I can stop the program from sending stuff to my log every second or so, but should sending at that rate really be the default?

Somewhat relatedly: having the config file in /etc means it will get overwritten with every update to the code, yes? If so, it's all the more important to have good defaults - though moving the config to /home/.config seems a good idea to me.

**Comment by rfjakob** [comment]
I think once a second is good to understand what is happening, and why earlyoom did something, when you run it in a terminal. If you run it as a service, it is easy to change the interval via `-r`.

But per default, I would like to be user-friendly for running on a terminal.

About the config file: earlyoom does not have a config file, I guess your Linux distribution has added it

**Comment by LinuxOnTheDesktop** [comment]
> About the config file: earlyoom does not have a config file, I guess your Linux distribution has added it

Oh. I had better check, then, that the file is actually being acted upon!

**Comment by LinuxOnTheDesktop** [comment]
From [your frontpage](https://github.com/rfjakob/earlyoom) (!):

```
Configuration file

If you are running earlyoom as a system service (through systemd or init.d), you can adjust its configuration via the file provided in /etc/default/earlyoom
```

**Comment by rfjakob** [comment]
Wow where does this come from. Oh I see m4he added it: https://github.com/rfjakob/earlyoom/commit/b52cc566acfb881f97195fc3d5494bf67ff121ea

Anyway, note that earlyoom does not read that config file! Your init system does. If you start earlyoom manually, the config file has no effect.

**Comment by rfjakob** [comment]
That's also noted on the front page:

> Please note that this configuration file has no effect on earlyoom instances outside of systemd/init.d.

**Comment by LinuxOnTheDesktop** [comment]
My mistake; I should have said that I was running earlyoom as a service. I do think that those who run earlyoon as a service will want to change the reporting interval. If I knew how to put together a pull request (properly), then I'd make one to add something in your documentation (on the website) saying something to that effect.
