### ISSUE TITLE
Use linux/sysinfo.h ?

### ISSUE THREAD

**Issue by kernc** [rfjakob/earlyoom#12]
Parsing _/proc/meminfo_ 10 times a second, could you for an even lighter footprint benefit from using _linux/sysinfo.h_ interface?

http://stackoverflow.com/questions/349889/how-do-you-determine-the-amount-of-linux-system-ram-in-c

**Comment by rfjakob** [comment]
Oh, I did not know this function, thanks! However, it does not seem to
provide whats is called MemAvailable in /proc/meminfo (only available in
recent kernels)

**Comment by kernc** [comment]
I see. `available` is [calculated as](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773) `freeram - something + something - ...`.  In your expert opinion, `totalram` and `freeram` and `totalswap` and `freeswap` don't build enough of a heuristic to justify a single syscall?

**Comment by rfjakob** [comment]
No, I don't think this is enough. You need to know the size of the page
cache, check out
https://github.com/rfjakob/earlyoom/blob/master/meminfo.c#L45 to see what I
the kernel does not provide MemAvailable

In short,

    available_guesstimate =  MemFree + Cached + Buffers - Shmem

**Comment by kernc** [comment]
Got it, sysinfo is missing cached. Thanks.
