### ISSUE TITLE
Improve memory metrics

### ISSUE THREAD

**Issue by haarp** [rfjakob/earlyoom#122]
Right now I'm having trouble configuring earlyoom in a way that doesn't kill processes too early or too late.

Using the defaults ```-m 10,5 -s 10,5```: If a process quickly uses a lot of memory, swapping and page thrashing starts rendering the system unusable, but earlyoom doesn't act, because it still sees a lot of free swap.

Disabling swap checks with ```-m 10,5 -s 100,100```: Bad actors are killed reliably, although always too soon. It seems MemAvailable, which earlyoom looks at, doesn't account for pages which can be swapped out. So low MemAvailable doesn't necessarily indicate a memory-starved system.

The crux is swap. Page thrashing can render the system unusable and unrecoverable, even if lots of swap is still available. But ignoring swap isn't the right choice either, as it *can* make a big difference (e.g. swapping out large tmpfs stores), as long as there's no thrashing. What to do?

In my experience the system can go up to 95% used (as seen by ```free```) before it starts acting up and threatening to become unrecoverable. Would an option that changes the metric used be a good idea? ```total```-```used``` seems to work for me, but it feels like a duct-tape solution. And I'm not sure what experiences others have.

Any ideas?

Thank you!

**Comment by hakavlad** [comment]
>memory metrics

>Any ideas?

https://lwn.net/Articles/759658/

You can already use https://github.com/hakavlad/nohang, it has PSI support (it needs Linux 4.20).

see also https://github.com/rfjakob/earlyoom/issues/100

**Comment by rfjakob** [comment]
Yes, this should work better when earlyoom gets PSI support. Progress is tracked at #100
