### ISSUE TITLE
Earlyoom fails

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#128]
I ran earlyoom and ran the script (it is memory hog, with rate=99 it works not very fast):

```python

#!/usr/bin/env python3

from signal import signal, SIGTERM

def signal_handler(signum, frame):
    print('Got signal {}'.format(signum))

signal(SIGTERM, signal_handler)

rate = 99

x = []

while True:
    x.append('#' * rate)
```

Result: script was killed by OOMK.

Earlyoom output:
```
mem avail:  1266 of 13855 MiB ( 9 %), swap free:  860 of 3071 MiB (28 %)
mem avail:   165 of 13855 MiB ( 1 %), swap free:  860 of 3071 MiB (28 %)
mem avail:    47 of 13855 MiB ( 0 %), swap free:  594 of 3071 MiB (19 %)
mem avail:     0 of 13855 MiB ( 0 %), swap free:  293 of 3071 MiB ( 9 %)
low memory! at or below SIGTERM limits: mem 10 %, swap 10 %
killing process 28367 "python3" with signal 15: badness 698, VmRSS 11793 MiB
process 28367 exited after 2.5 seconds
mem avail: 11239 of 13855 MiB (81 %), swap free:  812 of 3071 MiB (26 %)
mem avail: 11075 of 13855 MiB (79 %), swap free:  977 of 3071 MiB (31 %)
mem avail: 11040 of 13855 MiB (79 %), swap free: 1024 of 3071 MiB (33 %)
```

Script output:

```
Got signal 15
Killed
```

Syslog output:
```
апр 28 02:19:34 PC kernel: Out of memory: Kill process 28367 (python3) score 714 or sacrifice child
апр 28 02:19:34 PC kernel: Killed process 28367 (python3) total-vm:12438252kB, anon-rss:12083484kB, file-rss:2368kB, shmem-rss:0kB

```

**Comment by rfjakob** [comment]
This should be fixed now via
https://github.com/rfjakob/earlyoom/commit/614055e51dce9d68ffabe079d940fae678b7c239

**Comment by hakavlad** [comment]
Fixed, thanks

**Comment by hakavlad** [comment]
@rfjakob 

I ran memhog with rate = 9999 on VM with MemTotal = 2 G without swap.

In one of the cases system completely freezed (with earlyoom).

**Comment by hakavlad** [comment]
(fill rate = 6000 M/s doesn't help you in this case)

**Comment by hakavlad** [comment]
Could you explain what has changed in the algorithm? What delay values are used now?

**Comment by rfjakob** [comment]
After sending SIGTERM, earlyoom now waits until /proc/PID disappears.

The wait will be aborted after 10 seconds or if we get below the SIGKILL limits.

**Comment by rfjakob** [comment]
Fixed via https://github.com/rfjakob/earlyoom/commit/95a6bdbb47fc3414714a6facbf93ac136cea5fe4 . We are fast again.
```
mem avail:   139 of  2052 MiB ( 6 %), swap free:    0 of    0 MiB ( 0 %)
low memory! at or below SIGTERM limits: mem 10 %, swap 10 %
sending SIGTERM to process 7762 "python3": badness 859, VmRSS 1760 MiB
escalating to SIGKILL after 0.1 seconds
process exited after 0.2 seconds
```

**Comment by hakavlad** [comment]
Thanks.

>We are fast again.

Could you explain what has changed in the algorithm? What delay values are used now?

**Comment by rfjakob** [comment]
Now works like this. There is no fixed delay after killing.

1. Select victim and send SIGTERM
2. for i = 1 ... 100
    1. Check memory, if below SIGKILL limits, send SIGKILL to victim_pid
    2. Check if victim_pid is still visible. If not: break
    3. Sleep 100ms

**Comment by rfjakob** [comment]
And "victim_pid is still visible" works like this:
is_alive(): https://github.com/rfjakob/earlyoom/blob/master/meminfo.c#L107

1. Check if /proc/victim_pid/stat exists -> no -> return false
2. Check if process is a zombie -> return false
3. Return true

**Comment by hakavlad** [comment]
Thank you!

**Comment by hakavlad** [comment]
>Check if process is a zombie -> return false

Maybe it is not good idea:
see http://okturing.com/src/6437/body
In this case process has Z state, but it died in in 0.633 sec.
Earlyoom in this case would return false immediately (or in 100 ms) instead of 0.6 sec.

Dying processes (after get SIGKIL) usually have state Z or R.

Not only zombie processes have Z status, but also processes that receive the SIGKILL signal but have not yet freed up memory.

**Comment by rfjakob** [comment]
Can you capture a log that includes some time before SIGKILL?

What I have seen ( https://github.com/rfjakob/earlyoom/blob/master/contrib/mon.sh#L13 ), processes go into state R after SIGKILL, and to Z, or disappear, when all memory is freed.

**Comment by hakavlad** [comment]
Z-type dying: http://okturing.com/src/6439/body
R-type dying: http://okturing.com/src/6438/body

**Comment by hakavlad** [comment]
See http://okturing.com/src/6440/body

**Comment by hakavlad** [comment]
http://okturing.com/src/6440/body
Most memory freed at Z state. But only at the beginning.

**Comment by hakavlad** [comment]
We do not have a reliable sign of the end of the release of memory.

**Comment by rfjakob** [comment]
Interesting, thanks. But nothing we can do about it I'm afraid.

**Comment by hakavlad** [comment]
See https://github.com/rfjakob/earlyoom/issues/128#issuecomment-507019219
