### ISSUE TITLE
make: [Makefile:35: install] Error 1 (ignored)

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#129]
```
$ sudo make install
[sudo] password for user: 
sed "s|:TARGET:|/usr/local/bin|g;s|:SYSCONFDIR:|/etc|g" earlyoom.service.in > earlyoom.service
install -d /usr/local/bin/
install -m 755 earlyoom /usr/local/bin/
pandoc is not installed, skipping earlyoom.1 manpage generation
install -d /etc/default/
install -m 644 earlyoom.default /etc/default/earlyoom
install -d /etc/systemd/system
install -m 644 earlyoom.service /etc/systemd/system
chcon -t systemd_unit_file_t /etc/systemd/system/earlyoom.service
chcon: can't apply partial context to unlabeled file '/etc/systemd/system/earlyoom.service'
make: [Makefile:35: install] Error 1 (ignored)
systemctl enable earlyoom
Created symlink /etc/systemd/system/multi-user.target.wants/earlyoom.service → /etc/systemd/system/earlyoom.service.


```

**Comment by hakavlad** [comment]
(Ubuntu 19.04, Debian 9)

**Comment by rfjakob** [comment]
On Fedora 29, systemd unit files must have the right SELinux context:
```
$ ls -lZ /etc/systemd/system
total 68
drwxr-xr-x. 2 root root system_u:object_r:systemd_unit_file_t:s0     4096 Dec 31 20:56 basic.target.wants
drwxr-xr-x. 2 root root system_u:object_r:systemd_unit_file_t:s0     4096 Nov  5  2017 bluetooth.target.wants
lrwxrwxrwx. 1 root root system_u:object_r:systemd_unit_file_t:s0       41 Nov  5  2017 dbus-org.bluez.service -> /usr/lib/systemd/system/bluetooth.service
[...]
```
I imagine Debian 10 will do something similar. But in any case, an error in setting the context is ignored because of the "-" in front of the line in the Makefile.

**Comment by hakavlad** [comment]
```
$ ls -lZ /etc/systemd/system
итого 52
lrwxrwxrwx 1 root root ?    9 май 17  2018 apache2.service -> /dev/null
lrwxrwxrwx 1 root root ?    9 май 17  2018 apache-htcacheclean.service -> /dev/null


```

By the way, Debian/Ubuntu/Arch/Gentoo and most distros don't use SELinux.

**Comment by rfjakob** [comment]
Yeah, Debian is a bit slow, but looks like Debian 10 at least gets secure boot:
https://www.phoronix.com/scan.php?page=news_item&px=Debian-10-Testing-Secure-Boot

**Comment by hakavlad** [comment]
>Debian 10 at least gets secure boot

What does this have to do with SELinux context?

**Comment by marc1uk** [comment]
>But in any case, an error in setting the context is ignored because of the "-" in front of the line in the Makefile.
Am I right in interpreting this to means the installation is successful, since the error is ignored?
I feel this might be worth putting in the README as a warning to users on these systems.

**Comment by hakavlad** [comment]
@marc1uk PR are welcome

**Comment by LinuxOnTheDesktop** [comment]
I couldn't see that comment on https://github.com/rfjakob/earlyoom - and consequently I installed and the removed and then reinstalled earlyoom, because I thought there was a problem.
