### ISSUE TITLE
Error: Could not find a process to kill

### ISSUE THREAD

**Issue by kernc** [rfjakob/earlyoom#13]
Got some process to eat the whole of RAM. earlyoom appears to have crashed.

If it's relevant, I don't have swap.
```
$ sudo systemctl status earlyoom
● earlyoom.service
   Loaded: loaded (/etc/systemd/system/earlyoom.service; enabled)
   Active: failed (Result: exit-code) since Mon 2016-02-08 00:05:04 CET; 3 days ago
  Process: 699 ExecStart=/usr/local/bin/earlyoom (code=exited, status=9)
 Main PID: 699 (code=exited, status=9)

Feb 08 00:05:04 zoob earlyoom[699]: earlyoom v0.7-10-gb4c6bc0
Feb 08 00:05:04 zoob earlyoom[699]: mem total: 31600 MiB, min: 3160 MiB (10 %)
Feb 08 00:05:04 zoob earlyoom[699]: swap total: 0 MiB, min: 0 MiB (10 %)
Feb 08 00:05:04 zoob earlyoom[699]: Error: Could not find a process to kill
Feb 08 00:05:04 zoob systemd[1]: earlyoom.service: main process exited, code=exited, status=9/n/a
Feb 08 00:05:04 zoob systemd[1]: Unit earlyoom.service entered failed state.
```

**Comment by rfjakob** [comment]
Interesting. This means earlyoom tried but could not kill any process and
gave up. I will try to find out how this can happen, and make earlyoom try
again later.

**Comment by kernc** [comment]
> how this can happen

Apparently [no process had `oom_score` greater than `victim_points`](https://github.com/rfjakob/earlyoom/blob/b4c6bc040ce6ebfc70084fbd79b59bccd433e48a/kill.c#L112) (0)?

**Comment by rfjakob** [comment]
That would mean that there was no process using more than 0.1% ram, hence
oom_score was zero for all. Lots of small processes pushed the box into
oom. Does that sound plausible?

**Comment by kernc** [comment]
As a matter of fact, it does. :smile:
I don't think earlyoom should quit in that case, though.

**Comment by rfjakob** [comment]
Should be fixed now. If oom_score is equal, I use VmRss to decide which process to kill.

**Comment by kernc** [comment]
Should close #10 as well. Thanks! Will report how it's working.

**Comment by rfjakob** [comment]
Assuming fixed.
