### ISSUE TITLE
escalating to SIGKILL: Why? (need to fix output)

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#131]
```
$ earlyoom -m 50,0
earlyoom v1.3-rc1-12-g8887f63
mem total: 13855 MiB, swap total:    0 MiB
sending SIGTERM when mem <= 50 % and swap <= 10 %,
        SIGKILL when mem <=  0 % and swap <=  5 %
Could not lock memory - continuing anyway: Cannot allocate memory
mem avail:  9700 of 13855 MiB (70 %), swap free:    0 of    0 MiB ( 0 %)
mem avail:  9701 of 13855 MiB (70 %), swap free:    0 of    0 MiB ( 0 %)
mem avail:  9693 of 13855 MiB (69 %), swap free:    0 of    0 MiB ( 0 %)
...
mem avail:  9690 of 13855 MiB (69 %), swap free:    0 of    0 MiB ( 0 %)
mem avail:  9690 of 13855 MiB (69 %), swap free:    0 of    0 MiB ( 0 %)
mem avail:  9698 of 13855 MiB (69 %), swap free:    0 of    0 MiB ( 0 %)
mem avail:  9642 of 13855 MiB (69 %), swap free:    0 of    0 MiB ( 0 %)
mem avail:  6815 of 13855 MiB (49 %), swap free:    0 of    0 MiB ( 0 %)
low memory! at or below SIGTERM limits: mem 50 %, swap 10 %
sending SIGTERM to process 12006 "python3": badness 209, VmRSS 2891 MiB
escalating to SIGKILL after 2.4 seconds
process exited after 2.8 seconds
mem avail:  9806 of 13855 MiB (70 %), swap free:    0 of    0 MiB ( 0 %)
mem avail:  9801 of 13855 MiB (70 %), swap free:    0 of    0 MiB ( 0 %)
mem avail:  9786 of 13855 MiB (70 %), swap free:    0 of    0 MiB ( 0 %)
mem avail:  9779 of 13855 MiB (70 %), swap free:    0 of    0 MiB ( 0 %)
```

Seems like only SIGTERM threshold exceeded. Need more info in the output: why earlyoom sends SIGKILL.

**Comment by hakavlad** [comment]
>process exited after 2.8 seconds

After SIGTERM or after SIGKILL? Please fix output and add more info.

**Comment by hakavlad** [comment]
```
pid 31600: badness   0 vm_rss   5376 gvfs-udisks2-vo
pid 31608: badness   0 vm_rss   4228 gvfs-goa-volume
pid 31617: badness   0 vm_rss   4200 gvfs-afc-volume
pid 31622: badness   0 vm_rss   4108 gvfs-mtp-volume
pid 31626: badness   0 vm_rss   4496 gvfs-gphoto2-vo
pid 31647: badness   1 vm_rss  20564 gvfsd-metadata
pid 31799: badness   0 vm_rss   5164 lightdm
pid 31873: badness   0 vm_rss   4744 gnome-keyring-d
sending SIGTERM to process 12201 "python3": badness 636, VmRSS 8799 MiB
```

Please fix debug mode: add sleep time info after sending SIGTERM.

**Comment by hakavlad** [comment]
>selecting victim and sending signal took 10022.437 ms

Is it OK?

IMHO actually selecting victim and sending signal took 8 ms. Please fix output.

**Comment by hakavlad** [comment]
Also memory reporting is stopped in the 'Sending SIGTERM' loop.

**Comment by hakavlad** [comment]
Could you extend debug mode: what happens in the 'Sending SIGTERM' loop? Print all events.

**Comment by rfjakob** [comment]
Debug output enhanced, now looks like this

    selecting victim took 6.900 ms
    sending SIGTERM to process 2828 "membomb": badness 754, VmRSS 18044 MiB
    mem avail:  2493 of 23952 MiB (10 %), swap free:    0 of    0 MiB ( 0 %)
    process state: R
    mem avail:  2250 of 23952 MiB ( 9 %), swap free:    0 of    0 MiB ( 0 %)
    process state: R
    mem avail:  2008 of 23952 MiB ( 8 %), swap free:    0 of    0 MiB ( 0 %)
    process state: R
    mem avail:  1766 of 23952 MiB ( 7 %), swap free:    0 of    0 MiB ( 0 %)
    process state: R
    mem avail:  1524 of 23952 MiB ( 6 %), swap free:    0 of    0 MiB ( 0 %)
    process state: R
    mem avail:  1283 of 23952 MiB ( 5 %), swap free:    0 of    0 MiB ( 0 %)
    escalating to SIGKILL after 0.5 seconds
    process state: R
    mem avail:  2607 of 23952 MiB (10 %), swap free:    0 of    0 MiB ( 0 %)
    process state: R
    mem avail:  4349 of 23952 MiB (18 %), swap free:    0 of    0 MiB ( 0 %)
    process state: R
    mem avail:  6471 of 23952 MiB (27 %), swap free:    0 of    0 MiB ( 0 %)
    process state: R
    mem avail:  8867 of 23952 MiB (37 %), swap free:    0 of    0 MiB ( 0 %)
    process state: R
    mem avail: 11325 of 23952 MiB (47 %), swap free:    0 of    0 MiB ( 0 %)
    process state: R
    mem avail: 13806 of 23952 MiB (57 %), swap free:    0 of    0 MiB ( 0 %)
    process state: R
    mem avail: 16295 of 23952 MiB (68 %), swap free:    0 of    0 MiB ( 0 %)
    process state: R
    mem avail: 18783 of 23952 MiB (78 %), swap free:    0 of    0 MiB ( 0 %)
    process state: R
    mem avail: 20574 of 23952 MiB (85 %), swap free:    0 of    0 MiB ( 0 %)
    process exited after 1.4 seconds

Not sure about the regular output, I think it is enough info, but maybe I should add an example for how to interpret into the README.

**Comment by hakavlad** [comment]
OK, thanks.
