### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#133]
"Хотелось бы ОТ ВСЕЙ ДУШИ поблагодарить разработчиков(-ка) и спросить его Яндекс.Кошелёк.

rfjakob, я твой должник. Ты даже не представляешь от какого головняка ты меня спасаешь своей программулиной."
https://www.opennet.ru/opennews/art.shtml?num=50809

(user wants to make a donation)

**Comment by rfjakob** [comment]
I'm flattered but I don't take donations at this time. Maybe send a nice postcard instead? I can send you the address via private message.
