### ISSUE TITLE
How to use notify_all_users.py?

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#136]
I noticed that the script `notify_all_users.py` was added in `contrib` dir. But there is no documentation for it (in readme and man). How to use this script to notify all users?

I tried to run this script, but the notification was not shown:

```
$ sudo ./notify_all_users.py -i dialog-warning earlyoom "killing process X"
No summary specified.
```

![pic](https://i.imgur.com/YBsuf3T.png)

**Comment by rfjakob** [comment]
Fixed by https://github.com/rfjakob/earlyoom/commit/23bb71aa82186fdfb1315245728cf74c3d7dab73 , thanks.

Documentation is only provided in the help text.

**Comment by hakavlad** [comment]
Users will not know about the existence of this script, if they install the script from the repository of their distro. Now the existence of the script can be found only when reading issues and changelog.

Maybe it would be a good idea install the script via `make` in `/usr` and mention its existence in manpage.

Also maybe add in /etc/default/earlyoom:
```
# Examples:
# EARLYOOM_ARGS="-N notify_all_users.py"
```
