### ISSUE TITLE
Test fail possibly on a headless machine

### ISSUE THREAD

**Issue by yangfl** [rfjakob/earlyoom#137]
https://github.com/rfjakob/earlyoom/blob/1d0575f05266a4ecce21773f8686e59e44544518/tests/cli_test.go#L75

During building: https://buildd.debian.org/status/fetch.php?pkg=earlyoom&arch=amd64&ver=1.3-1&stamp=1562521178&raw=0

Test failed with: `
cli_test.go:129: stdout should contain "^ new victim (higher badness)", but does not`

Looks like `badness = p.oom_score;`, I guess it is because no one adjusted their oom_score in a lightweight environment.

**Comment by rfjakob** [comment]
Good catch, fixed, thanks!
