### ISSUE TITLE
Integration with Nagios, Zabbix etc

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#138]
How to integrate earlyoom with monitoring systems? Are there add-ons for collecting metrics from earlyoom for these systems? I think it would be useful to track earlyoom events using centralized monitoring systems for owners of large server infrastructure.

**Comment by rfjakob** [comment]
Well, you could parse syslog, or you could run some command using `-N` that sends an event to Nagios

**Comment by hakavlad** [comment]
OK, thank you!
