### ISSUE TITLE
[KDE] notifications "don't deserve to be in history"

### ISSUE THREAD

**Issue by carlocastoldi** [rfjakob/earlyoom#139]
Since 5.16.2, Plasma decided not to keep non-configurable notifications in history.
Since the notifications sent by earlyoom aren't detected as "configurable", now in Plasma you have just a few seconds to see that you are low on memory and which process was killed in order to free up some space.

I genuinely don't know how hard it could be to properly configure notifications, but do you think it would be possible to work around this little (but important) inconvenience?

sources:
KDE Plasma 5.16.2 changelog: https://kde.org/announcements/plasma-5.16.2.php
KDE developer talking about the changes: https://www.reddit.com/r/kde/comments/c7w6u5/no_plasma_notifications_history_after_update_to/

> **ngraham** accepted this revision.
> "+1, if an app can't bother to set this stuff properly for itself, then it's either not very important or doesn't deserve to be in the history. Works perfectly."

P.S. oh and thanks! This is a super great project, I'm so happy i've found out about its existence!

**Comment by rfjakob** [comment]
I read through the thread - wow, these KDE people are pretty uncompromising!

Anyway, what earlyoom does at the moment is running
```
notify-send earlyoom "hello world"
```
You can just run it a terminal to try it out. When you run
```
notify-send --hint=string:desktop-entry:earlyoom earlyoom "hello world"
```
instead, does it stay in the history?

**Comment by carlocastoldi** [comment]
> You can just run it a terminal to try it out. When you run
> 
> ```
> notify-send --hint=string:desktop-entry:earlyoom earlyoom "hello world"
> ```
> 
> instead, does it stay in the history?

No, i'm afraid it does not stay in the history :\

**Comment by hakavlad** [comment]
No way. But history is available in journal:

sudo journalctl -eu earlyoom

**Comment by carlocastoldi** [comment]
Ok that can already help a lil bit :+1:

**Comment by noahadvs** [comment]
> > You can just run it a terminal to try it out. When you run
> > ```
> > notify-send --hint=string:desktop-entry:earlyoom earlyoom "hello world"
> > ```
> > 
> > 
> > instead, does it stay in the history?
> 
> No, i'm afraid it does not stay in the history :\

Earlyoom needs to actually have its own `.desktop` file installed for that command to work correctly.

**Comment by noahadvs** [comment]
I have to put this in a tarball since GitHub doesn't let me upload desktop files, but extract this to `~/.local/share/applications` and try the command again.

[earlyoom.tar.gz](https://github.com/rfjakob/earlyoom/files/3488711/earlyoom.tar.gz)

**Comment by carlocastoldi** [comment]
> I have to put this in a tarball since GitHub doesn't let me upload desktop files, but extract this to ~/.local/share/applications and try the command again.

That doesn't work either :/
Not even if i move the .desktop to /usr/share/applications/

FYI EARLYOOM_ARGS is `EARLYOOM_ARGS="-r 60 -m 5 -N 'sudo -u carlo DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send -u critical -a earlyoom' --avoid '(^|/)(init|Xorg)$'"`

(and sorry if i waited this long to test this, but i was away)

**Comment by noahadvs** [comment]
@carlocastoldi Try this:
```
EARLYOOM_ARGS="-r 60 -m 5 -N 'sudo -u carlo DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send -u critical --hint=string:desktop-entry:earlyoom -a earlyoom' --avoid '(^|/)(init|Xorg)$'"
```

**Comment by noahadvs** [comment]
@rfjakob This problem should be solvable if you just include a desktop file and have it installed to `/usr/share/applications`.

**Comment by rfjakob** [comment]
I'll accept a PR that adds that into the `contrib` folder, but I don't want to install it by default

**Comment by hakavlad** [comment]
>X-KDE-SubstituteUID=false
>X-KDE-Username=

@noahadvs Are these keys really necessary?

Will the problem be resolved with the following file?

```
[Desktop Entry]
Type=Application
Version=1.0
Name=earlyoom
Exec=earlyoom --version
StartupNotify=false
NoDisplay=true
```

**Comment by hakavlad** [comment]
@noahadvs BTW, the file you proposed is not valid:

```
$ desktop-file-validate earlyoom.desktop
earlyoom.desktop: warning: value "earlyoom" for key "Comment" in group "Desktop Entry" looks redundant with value "earlyoom" of key "Name"
earlyoom.desktop: error: file contains key "Path[$e]" in group "Desktop Entry", but key names must contain only the characters A-Za-z0-9- (they may have a "[LOCALE]" postfix)
earlyoom.desktop: warning: boolean key "Terminal" in group "Desktop Entry" has value "0", which is deprecated: boolean values should be "false" or "true"
earlyoom.desktop: warning: key "TerminalOptions" in group "Desktop Entry" is deprecated
```

**Comment by noahadvs** [comment]
Whoops, looks like I forgot about this.

@hakavlad, I didn't run any validation tools, I think I just generated the desktop file with KMenuEdit.

This is the file I currently use:

```
[Desktop Entry]
Name=earlyoom
GenericName=earlyoom
Comment=This desktop entry is only used for notifications
Icon=applications-other
Exec=earlyoom
Type=Application
```

**Comment by hakavlad** [comment]
>This is the file I currently use

Do you use it with latest KDE, and it works? Did you test it with `/usr/share/applications`?

**Comment by noahadvs** [comment]
@hakavlad Yes, all of my KDE software is on git master. I originally put the desktop file in `~/.local/share/applications`, but `/usr/share/applications` works just fine too.

**Comment by noahadvs** [comment]
BTW, this desktop file isn't actually necessary if you use `notify-send -u critical`. setting the urgency to critical makes the notification sit on the screen until it is manually closed. Manually closing a notification also makes it not appear in the history, because the user had to see it in order to close it.

**Comment by Pointedstick** [comment]
> BTW, this desktop file isn't actually necessary if you use `notify-send -u critical`. Setting the urgency to critical makes the notification sit on the screen until it is manually closed. Manually closing a notification also makes it not appear in the history, because the user had to see it in order to close it.

That seems like it may be ideal resolution, if indeed the notification in question is communicating critically important information.

**Comment by hakavlad** [comment]
`-u critical` blocks all other new notifications in GNOME. But may be OK for KDE Plasma. I think this should be explained in FAQ.

**Comment by rfjakob** [comment]
I don't think `-u critical` is right. The critical situation is already over, earlyoom has killed the process.

I'll accept a PR for a desktop file, though.

**Comment by hakavlad** [comment]
System Settings -> Notifications -> Applications: Configure -> Other Applications -> [+]Show in history

It works in KDE Plasma 5.18.4.
