### ISSUE TITLE
incorrect instruction for -N key

### ISSUE THREAD

**Issue by admzzz** [rfjakob/earlyoom#141]
```
# ls /run/user/1000/bus
ls: cannot access '/run/user/1000/bus': No such file or directory
# ls /run/user/1000
dconf  gvfs  keyring  pulse  systemd
```
how to find the proper path for dbus?
linux mint 18.2 cinnamon
```
$ set | grep DBUS
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-b3nnK88UNh,guid=fa736a01a3747996a5159d315d492ede
$ ls /tmp/dbus-b3nnK88UNh
ls: cannot access '/tmp/dbus-b3nnK88UNh': No such file or directory
```

**Comment by hakavlad** [comment]
>how to find the proper path for dbus?

@admzzz  use notify_all_users.py from https://github.com/rfjakob/earlyoom/tree/master/contrib

earlyoom -N notify_all_users.py

https://github.com/rfjakob/earlyoom/tree/master/contrib/notify_all_users.py

**Comment by admzzz** [comment]
@hakavlad 
фэнкс э лот, ит вокс. ;-)
