### ISSUE TITLE
LDFLAGS?

### ISSUE THREAD

**Issue by zvezdochiot** [rfjakob/earlyoom#143]
https://github.com/rfjakob/earlyoom/blob/b267304574bf64eec34538820b3c98de00a9cbb1/Makefile#L20

Maybe:
```make
LDFLAGS += -lrt
...
earlyoom: $(wildcard *.c *.h) Makefile
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(wildcard *.c)
```
Not?

**Comment by rfjakob** [comment]
Why should we link with the "rt" library?
