### ISSUE TITLE
earlyoom was proposed to be enabled by default in Fedora 32 Workstation

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#148]
Change proposal: https://fedoraproject.org/wiki/Changes/EnableEarlyoom.
Issue: https://pagure.io/fedora-workstation/issue/119.

**Comment by hakavlad** [comment]
Mailing https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/YXDODS3G4YCS7MT4J2QJMJ7EXCVR7NQ2/#W73ZVOIRNNW4YVQT6FNSLI6GHUJCZSKY

**Comment by hakavlad** [comment]
Summary/Minutes from today's FESCo Meeting (2020-02-03)

#2320 F32 System-Wide Change: Enable EarlyOOM (decathorpe, 15:09:19) * FESCo acknowledges the Workstation WG's decision and does not want to overrule (decathorpe, 15:13:33)
-- https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/DU5G4I6QQ73HCJYUIOINTBQ3HV7JPOOG/

See also https://pagure.io/fesco/issue/2320.

**Comment by hakavlad** [comment]
- 2320 F32 System-Wide Change: Enable EarlyOOM (decathorpe, 15:09:19)
- FESCo acknowledges the Workstation WG's decision and does not want to overrule (decathorpe, 15:13:33)

-- https://pagure.io/fesco/issue/2320#comment-624953

**Comment by rfjakob** [comment]
Wow! Thanks for the updates!

**Comment by hakavlad** [comment]
@rfjakob 

That's not all.

TODO:
ask rfj:

- systemd unit hardening
- change the default -m PERCENT to 4%
- remove `-p` (setting oom_score_adj=-1000 is very bad practice).

**Comment by hakavlad** [comment]
default in F32W:
```
EARLYOOM_ARGS="-r 0 -m 4 -M 409600 --prefer '^Web Content$' --avoid '^(dnf|packagekitd|gnome-shell|gnome-session-c|gnome-session-b|lightdm|sddm|sddm-helper|gdm|gdm-wayland-ses|gdm-session-wor|gdm-x-session|Xorg|Xwayland|systemd|systemd-logind|dbus-daemon|dbus-broker|cinnamon|cinnamon-sessio|kwin_x11|kwin_wayland|plasmashell|ksmserver|plasma_session|startplasma-way|xfce4-session|mate-session|marco|lxqt-session|openbox)$'"
```

https://pagure.io/fedora-workstation/issue/119#comment-638366
https://pagure.io/fedora-workstation/issue/119#comment-638522

**Comment by hakavlad** [comment]
Enable EarlyOOM on Fedora KDE
https://fedoraproject.org/wiki/Changes/KDEEarlyOOM

**Comment by hakavlad** [comment]
https://fedoraproject.org/wiki/Changes/EnableSystemdOomd 

systemd-oomd enabled by default in F34 instead of earlyoom for all desktop variants.
