### ISSUE TITLE
'Avoiding to kill process names that match regex [. . .]' is bad English

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [rfjakob/earlyoom#149]
'Avoiding to kill process names that match regex [. . .]' is bad English, particularly because of the 'avoiding to'. I presume that the intended meaning is: 'Earlyoom will avoid killing any process that matches the following regular expression:'

So I suggest that you adopt the latter form of words.

**Comment by rfjakob** [comment]
That's the same structure as this, no? https://github.com/rfjakob/earlyoom/blob/master/main.c#L216

>         fprintf(stderr, "Prefering to kill process names that match regex '%s'\n", prefer_cmds);

Is this wrong, too?

**Comment by rfjakob** [comment]
I tried to keep the message short, does https://github.com/rfjakob/earlyoom/commit/c58d54884deabd9e41a9c55c46230dd55439816c look ok to you?

**Comment by LinuxOnTheDesktop** [comment]
Each of the new versions - the new versions of the two strings at issue - is an improvement. Yet, there is still the following problem. Each formulation - perhaps because it is not really a sentence but instead a clause that uses a participle ('X-ing') - leaves it unclear whether

1) some action is being taken now,
or
2) some policy is being announced - such that, if, _later_, then . .

I suspect that 2 is the case. If so, then I advise preceding each string with something like, 'Policy', such that one has, for example:

> 
Policy: prefer to kill <etc.>

That would be clear and also good English.
