### ISSUE TITLE
Run without root?

### ISSUE THREAD

**Issue by cwrau** [rfjakob/earlyoom#150]
Is there a possibility to run earlyoom as a normal user?

If I just run it, it tries to kill processes by other users, which of course fails.

Like a flag `-u` that tells earlyoom to just kill processes owned by the running user.

**Comment by hakavlad** [comment]
You can apply maximal restrictions via systemd unit:

```
[Unit]
Description=Early OOM Daemon
Documentation=man:earlyoom(1) https://github.com/rfjakob/earlyoom

[Service]
EnvironmentFile=-/etc/default/earlyoom
ExecStart=/usr/local/bin/earlyoom $EARLYOOM_ARGS
DynamicUser=true
PrivateTmp=true
PrivateNetwork=true
NoNewPrivileges=true
RestrictRealtime=yes
MemoryDenyWriteExecute=yes
ProtectKernelModules=true
ProtectKernelTunables=true
RestrictSUIDSGID=true
ProtectHome=true
SystemCallArchitectures=native
ReadOnlyPaths=/
CapabilityBoundingSet=CAP_KILL CAP_IPC_LOCK
AmbientCapabilities=CAP_KILL CAP_IPC_LOCK
MemoryMax=5M
MemorySwapMax=0
TasksMax=1

[Install]
WantedBy=multi-user.target
```

By the way, running from a regular user will break the GUI notification.

**Comment by hakavlad** [comment]
If you are interested in the possibility of not restricting the rights of earlyoom, namely the possibility of forcing earlyoom not to see the processes of other users, then you can take a look at nohang. If this daemon is launched from a regular user, then it does not see the processes of other users.

**Comment by cwrau** [comment]
Mh, I'd like to just launch earlyoom via the command, as used by my i3 config.

And the notifications work fine, that's how I saw that it tried to kill `systemd-coredump`.

I've taken a look at nohang, and I really dislike it, building somehow requires running systemd commands and this prevents automatic updates.

Also all configs are inside a file, which is badly documented.

The bad documentation is even documented on the project's README 🤣

If there is no option, and you don't want to add this feature, I'll just have to revert to running it with sudo and hope it doesn't kill anything important 😅

**Comment by hakavlad** [comment]
>systemd-coredump

This thing can generally be turned off, it can consume a lot of memory.

>building somehow requires running systemd commands

You can run this without systemd:

```
$ nohang
```

>If there is no option

What options do you need?

**Comment by cwrau** [comment]
Yeah, running works, but I'm already annoyed by building it^^

An option in earlyoom, so that it only kills processes of the user that ran earlyoom, aka me, aka uid 1000

**Comment by hakavlad** [comment]
>An option in earlyoom, so that it only kills processes of the user that ran earlyoom

earlyoom has no this option, nohang has this option

**Comment by hakavlad** [comment]
>Also all configs are inside a file, which is badly documented.

I can document right  now all what you need special for you. To force killing processes owned only specified user add in config:

```
# Add 2000 to the badness of user processes with eUID = 1000
@BADNESS_ADJ_RE_UID  2000  ///  ^1000$

# set min_badness to 1000 to prevent killing processes with badness < 1000.
min_badness = 1000
```

The daemon will not kill the processes of other users with such a config. User processes will receive maximum priority, and processes of other users will be protected from being killed by the daemon.

**Comment by cwrau** [comment]
Thanks, I'll consider it!

**Comment by rfjakob** [comment]
I think running as a normal user will lead to all kinds of weirdness. If another user consumes a lot of memory, *all the processes* of the first user will be killed.
