### ISSUE TITLE
How does this determine what processes to kill? 

### ISSUE THREAD

**Issue by Chaython** [rfjakob/earlyoom#155]
How does this determine what processes to kill? Is there anyway to control what this kills? I do see it says it kills the largest process but if the largest process is a VM with huge pages does it kill the vm? 
How does it manage huge pages on host? How well does it handle swap being disabled?

**Comment by rfjakob** [comment]
Hi, as explained in https://github.com/rfjakob/earlyoom#what-does-it-do , it looks for the largest oom_score. Yes it will kill the VM. I don't think hugepages make a difference. earlyoom works fine with and without swap.

If you want to protect your vm, you can use the `--avoid` option, see https://github.com/rfjakob/earlyoom#command-line-options
