### ISSUE TITLE
Don't prefer processes with negative oom_score_adj

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#159]
For example, `systemd-udevd` has `oom_score_adj`=-1000.
If I set `--prefer systemd-udevd`, it will get `badness`=300. 

```
фев 11 21:05:09 PC earlyoom[15282]: pid   363: badness 300 vm_rss   3636 systemd-udevd
фев 11 21:05:09 PC earlyoom[15282]:     ^ new victim (higher badness)
```

I think it's not OK.
We can assume that this is a critical process if it has such a low `oom_score_adj` value, and killing it could destroy the system.

My suggestion:
Do not increase badness of processes with negative `oom_score_adj`. At least don't prefer processes with `oom_score_adj`=-1000.

**Comment by rfjakob** [comment]
Hmm. We have to calculate `oom_score_before_adjustment + 300` and use that. However, I don't see a way to get `oom_score_before_adjustment`:
```
/proc/10269$ grep . comm oom_*
comm:systemd-udevd
oom_adj:-17
oom_score:0
oom_score_adj:-1000
```

**Comment by rfjakob** [comment]
I think if a user wants to have systemd-udevd killed, we will not prevent him from doing that, but I have documented the bug as https://github.com/rfjakob/earlyoom/commit/953cf959ed11298da234ee1eedb18f92c0e734e1 .
