### ISSUE TITLE
When /proc is mounted with hidepid=2, it doesn't work

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#161]
>earlyoom.service: drop root privileges
>Run as a random unprivilege user instead of as root,
>but add the capabilities CAP_KILL CAP_IPC_LOCK.
>https://github.com/rfjakob/earlyoom/commit/f2b45e6a18a0624032d289318569ad57c24fd419

When /proc is mounted with hidepid=2, it doesn't work. The Earlyoom service can only see its own pid.

**Comment by rfjakob** [comment]
Hi, what is hidepid?

**Comment by hakavlad** [comment]
```
proc /proc proc defaults,hidepid=2,gid=admin 0 0
```
Add this in /etc/fstab, and processes will can see proc directories of only the same UIDs.

See https://linux-audit.com/linux-system-hardening-adding-hidepid-to-proc/

**Comment by hakavlad** [comment]
How to test: 
```
# mount -o remount,hidepid=2 /proc
```

**Comment by rfjakob** [comment]
I think this is a similar situation as "/proc is not mounted". We can't do anything about it.

**Comment by grapeli** [comment]
No, it's not the same situation.
The solution is really simple.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/filesystems/proc.txt#n2045
> gid= defines a group authorized to learn processes information otherwise prohibited by hidepid=.

```
[Service]
SupplementaryGroups=proc
```

**Comment by rfjakob** [comment]
Is there a distribution that uses hidepid ?

**Comment by grapeli** [comment]
https://wiki.archlinux.org/index.php/Security#hidepid
Default? I do not know. I use under Archlinux. In the olden days I used 2.6 with grscecurity.

**Comment by hakavlad** [comment]
SupplementaryGroups= does not work with dynamic groups https://github.com/systemd/systemd/issues/8219

So, this may not work.

**Comment by hakavlad** [comment]
I set `SupplementaryGroups=proc` and got the output in the journal (with systemd 232 on Debian 9):
```
фев 29 11:47:52 PC systemd[1]: Started Early OOM Daemon.
фев 29 11:47:52 PC systemd[843]: earlyoom.service: Failed at step GROUP spawning /usr/local/bin/earlyoom: No such process
фев 29 11:47:53 PC systemd[1]: earlyoom.service: Main process exited, code=exited, status=216/GROUP
фев 29 11:47:53 PC systemd[1]: earlyoom.service: Unit entered failed state.
фев 29 11:47:53 PC systemd[1]: earlyoom.service: Failed with result 'exit-code'.
```

**Comment by hakavlad** [comment]
```
фев 29 11:47:52 PC systemd[843]: earlyoom.service: Failed at step GROUP spawning /usr/local/bin/earlyoom: No such process
```
-- this happens when supplementary group does not exist.

**Comment by hakavlad** [comment]
Mount proc with `hidepid=2,gid=adm` and set `SupplementaryGroups=adm` in the unit, and it works well with systemd 232.

**Comment by grapeli** [comment]
It also works for me (SupplementaryGroups)

This is a distribution level solution. Just mention it explicitly in **README**.

**Comment by rfjakob** [comment]
Added to the wiki as https://github.com/rfjakob/earlyoom/wiki/proc-hidepid , thanks

**Comment by willnode** [comment]
If anyone stumbles upon this issue with hidepid=4, the `gid=` option [may doesn't work](https://superuser.com/q/1905316/498815).
