### ISSUE TITLE
Change default -m value

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#162]
The default threshold of 10% of available memory is criticized for excessive waste:

>In the case of no swap, I agree this becomes difficult to use a single percentage. 1% is too low for e.g. 8GiB RAM system, and is too high for e.g. 64GiB RAM system. This might be the most significant liability of the feature. 

>Even though no swap isn't our default configuration, and the installer warns users when swap isn't configured, I think it's sufficiently common users have systems with lots of RAM forego swap. I'm not convinced merely documenting users will experience OOM killing of processes at 5% of 32-64GiB, e.g. 1.6-3.2GiB free RAM, is acceptable. 

https://pagure.io/fedora-workstation/issue/119#comment-618480

>if there is no swap, earlyoom has only a single low watermark, free RAM. Once that gets to 5% on a 64GiB system, i.e. 3.2GiB free, it's going to kill something. That's the problem. 3.2GiB free is plenty of RAM to keep chugging away, so in the no swap case I think it needs a different metric for what the low watermark is.

https://pagure.io/fedora-workstation/issue/119#comment-618574

>4% means SIGTERM happens at ~2.6G free on a 64G RAM computer; while SIGKILL happens at ~82M on a 4G RAM computer. The former is high, the latter is low. I never see less than ~130M free in the totally hung state.

https://pagure.io/fedora-workstation/issue/119#comment-618616

>Using a percentage to decide "almost out of memory" is going to hurt on systems with large amounts of memory be it a 32gb desktop or a 2tb server. You'd have plenty of memory left and it starts killing processes ...

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/RRLBHPP5B6S3S26VIEKYEVQ7RZYD6B72/

>I agree this is the most significant liability of the proposal right now. I mention it in: https://pagure.io/fedora-workstation/issue/119#comment-618480

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/2AIJX5DGV2BJHXLFW2JDXN4O3TPOVSQR/

>It might be. And it might need to be tweaked. Perhaps 6% for SIGTERM and 3% for SIGKILL. Or even 5% and 2.5%. For sure using a percentage of RAM and swap is too simplistic. But it's easy for users to understand. Something more sophisticated, based on kernel pressure stall information would likely be better, and folks are working on that.

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/EYJRMNEMTQZLBFB4RRETOGKUJ3V3CXL3/

>Yes that would be a way better metric than a percent value which is either to close to full ram or to early if you have lots of ram. 6% of 4GB is 254MB while for 32GB its almost 2GB - killing processes while you have 2GB left is just wasteful.

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/IHC2IQ5ZFKHGHX4HSTHECTEXTPT464JI/

>On my 32GB laptop that means 3.2GB of RAM gets unusable. And on my 64GB machine I'm being robbed of 6.4GB. Wow. How low can these numbers be pushed? Even 3% would be 1GB out of 32GB.

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/IJMEYHEZFP4YD24MGXV435UL3UGGA4MJ/

>If you don't have swap, yes RAM becomes the determining factor and I agree that on systems with a lot of RAM, 10% is too high.

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/QA4AGTR7H4NNT3KVSCNOKBPN7VOTU6G2/

I am sure that the default threshold of 4% memory will be a better value than 10%. A threshold of 4% is absolutely sufficient to prevent OOM and maintain sufficient responsiveness. Please consider changing the default memory threshold.

**Comment by rfjakob** [comment]
I wonder if we should make the default staggered, something like

Up to 4GB RAM: 10%
Up to 8GB RAM: 4%
Up to 64GB RAM: 2%
Above 64GB RAM: 1%

**Comment by hakavlad** [comment]
I suggest  something like

Up to 3GB RAM: 6%
Up to 6GB RAM: 4%
Up to 16GB RAM: 2%
Above 16GB RAM: 1%

I did not see any problems even with a threshold of 4% and 2GB MemTotal.

Do you plan to hardcode these values?

**Comment by rfjakob** [comment]
Probably good enough to have a cap on the values, like "10% or 500mb, whichever is less"

The the cap should be set through a new command line option, with some sensible default

**Comment by rfjakob** [comment]
Actually, we can use the old command line options. When you pass both a percentage and a megabyte value, the lower value could be used

**Comment by hakavlad** [comment]
Maybe set additional flag:
--max-m 500M.  - The threshold is determined by the percent -m, but must not exceed the threshold --max-m.

**Comment by hakavlad** [comment]
Note that Fedora guys are looking forward to change.

**Comment by hakavlad** [comment]
>When you pass both a percentage and a megabyte value, the lower value could be used

I like it. And I suggest 4% and 500M. 4% is OK even with 2GB MemTotal.

**Comment by hakavlad** [comment]
```
$ earlyoom -m 4 -M 444444
earlyoom v1.3.1-59-gbf0b04c
fatal: can't use both -m and -M
```

Please fix it, and the problem will be solved.

**Comment by hakavlad** [comment]
>Change default -m value

The problem is not yet solved, 10% is default PERCENT.

BTW, 3 alerts https://lgtm.com/projects/g/rfjakob/earlyoom/alerts/?mode=list

And we waiting for the next release with new -m/-M default values. Thanks.
