### ISSUE TITLE
1.4 does not respect $PREFIX

### ISSUE THREAD

**Issue by xvitaly** [rfjakob/earlyoom#166]
Generated systemd unit:

```
ExecStart=/usr/local/bin/earlyoom $EARLYOOM_ARGS
```

Must me `/usr/bin`, because `PREFIX=/usr`.

**Comment by xvitaly** [comment]
Sorry, it was a packaging issue. Now we need to pass overrides both for %build and to %install changes.

@rfjakob Do you want to change build system to meson? I can help you with with meson.

**Comment by rfjakob** [comment]
Meson... I'm not sure, will things get simpler with meson?

**Comment by xvitaly** [comment]
> I'm not sure, will things get simpler with meson?

Yes, and much more stable. If you don't like Meson, I can suggest Cmake instead.
