### ISSUE TITLE
Output spam | Hide debug messages

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#171]
>Is it necessary to log every minute? It makes the journal less readable. The background checking can run as frequently as possible, but it would be nice if it logged very rarely when there's enough free memory, and increased the interval when the memory is getting filled up. When I have 80% of memory free, such frequent logging seems superfluous. Or is just debugging feature that will get turned off on F32 final release?

https://pagure.io/fedora-workstation/issue/119#comment-631173

In fact, option `-r` is a debug option.

I think memory reports should be disabled by default.

I think
```
EARLYOOM_ARGS="-r 0 -m 4 -M 500000"
```
is good default.

**Comment by rfjakob** [comment]
No i like the memory report, fedora can set it to 0 if they want.

**Comment by kparal** [comment]
I didn't ask for disabling the messages completely, but for being considerably less frequent when there's no memory pressure.

**Comment by hakavlad** [comment]
>I've tested earlyoom with F32 beta on special VM with 2 GB RAM within a week and earlyoom pushed 500 MB of garbage to journald.

https://pagure.io/fedora-workstation/issue/119#comment-633658
