### ISSUE TITLE
-r flag and flooding of log

### ISSUE THREAD

**Issue by IlyaIndigo** [rfjakob/earlyoom#177]
Problem. earlyoom floods the /var/log/messages log with unnecessary memory status messages.
I want to see only events sending signals to processes in the log.
Does the -r flag affect only the state of memory logging, or also the frequency of polling the memory?
Will -r0 earlyoom work correctly?

**Comment by IlyaIndigo** [comment]
Apparently, it does not affect the polling frequency, but only on logging.
Why is logging of memory state every second turned on by default?
This is for debugging only!
Many people think that this flag depends on the polling frequency for sending signals to processes.
I propose to set it to 0 by default and to emphasize in the manual that this parameter only affects logging and does not affect the actual polling rate.

**Comment by rfjakob** [comment]
Yes 0 works, and this is documented in https://github.com/rfjakob/earlyoom/blob/master/MANPAGE.md#-r-interval .

The default when running as a service is 60 seconds, but you can customize it to your likings:
https://github.com/rfjakob/earlyoom/blob/master/earlyoom.default#L5

**Comment by IlyaIndigo** [comment]
man earlyoom
-r INTERVAL
       memory report interval in seconds **(default 1)**, set to 0 to  disable  completely.   With  earlyoom
       v1.2  and higher, floating point numbers are accepted.  Due to the adaptive poll rate, when there
       is a lot of free memory, the actual interval may be up to 1 second longer than the setting.

The emphasis is on the fact that in 1.2+ you can use decimal numbers, and not on the fact that this affects ONLY logging and does not affect the operation of the service.

**Comment by hakavlad** [comment]
@IlyaIndigo  https://github.com/rfjakob/earlyoom#configuration-file

Default in the config:
```
EARLYOOM_ARGS="-r 60"
```

See also https://github.com/rfjakob/earlyoom/issues/171.

**Comment by IlyaIndigo** [comment]
Well, at least fix it in the man page.
And also think about why system administrators, looking at the logs, see this even every 60 seconds, that is, that is, flipping a log for a day, 1440 lines more per day and 433200 lines per month?

**Comment by rfjakob** [comment]
I tried to make the man page clearer ( https://github.com/rfjakob/earlyoom/commit/c1180becd175201a1539bf96e6f3f81af2406002 ) and I set `-r 3600` in the earlyoom service config file earlyoom.default  https://github.com/rfjakob/earlyoom/commit/e1c74d918c3951e0ec20bd8817ab55530e020491

Thanks

**Comment by hakavlad** [comment]
thanks

**Comment by IlyaIndigo** [comment]
> (default 1.0)
Change please to (default 3600.0)

**Comment by rfjakob** [comment]
When you execute earlyoom without parameters, the default is used, which is unchanged: 1 second

**Comment by LeDechaine** [comment]
This bug is back. My /var/log/syslog is flooded every second even with EARLYOOM_ARGS="-r 3600" in /etc/default/earlyoom

/etc/default/earlyoom is useless because earlyoom just does not read it.

Fixed by cleaning earlyoom, which is useless anyway, and adding all ARGS in one line earlyoom.service, for example:
`ExecStart=/usr/bin/earlyoom -r 3600 -m 5 -n --avoid '(^|/)(init|X|sshd|firefox)$'`

Using Debian 13 / stable.

**Comment by rfjakob** [comment]
I checked what Debian does ( https://packages.debian.org/trixie/amd64/earlyoom/download ). Looks correct. This is in earlyoom.service:

```
EnvironmentFile=-/etc/default/earlyoom
ExecStart=/usr/bin/earlyoom $EARLYOOM_ARGS
```

EARLYOOM_ARGS should work just fine.
