### ISSUE TITLE
Priority kill

### ISSUE THREAD

**Issue by felipec** [rfjakob/earlyoom#18]
Basically I always run out of memory in the same scenario: I open Dota, I open a few Chromium tabs, and eventually when Dota starts the game I run out of memory. I want Chromium to be killed, not Dota.

So for me either banning a process from being killed, or prioritizing a process to get killed would do the trick. It would be nice if there was a configuration for that.

**Comment by bsdson** [comment]
+1
my scenario is similar, with a VM not Dota.
I'd like a white-list and/or a black-list,
to always kill Chrome or to always not kill VM.

**Comment by rfjakob** [comment]
earlyoom kills processes based on the value in `/proc/1234/oom_score`, which is basically a number between 0 and 1000, proportional to the memory usage.
There is a built-in mechanism to adjust that score in `/proc/1234/oom_score_adj`. Now Chrome sets this to 300, which is pretty high, so I'm surprised that Dota is killed first.
Can you start earlyoom with the "-d" option and post the output after something was killed?

@bsdson : Can you post the oom_score value of the VM process and the Chrome processes? Once you have that, you can decide for a **negative** value to write into oom_score_adj for the VM.

**Comment by rfjakob** [comment]
PS: Bash oneliner to print out the oom_score value for all Chrome processes:

    for i in $(pgrep chrome); do cat /proc/$i/oom_score; done

**Comment by joeytwiddle** [comment]
In [my branch](https://github.com/joeytwiddle/earlyoom/blob/rich_score_adj_mem/main.c#L18:L24) I've added priority to kill Chrome tabs, using regexps. This is nice and flexible but not as simple and memory efficient as the original. (My branch also prioritises old processes more, and high memory processes less.)

Anyway rfjakob is right, Chrome usually prioritises its own processes for killing via `oom_score_adj`, so it is surprising that they weren't killed before the VM or Dota.

**Comment by edgimar** [comment]
@joeytwiddle Thanks for working on that -- it's convenient to be able to adjust priorities via regexps.  It would be nicer, however, if one could specify these in a config-file and/or as command-line args, rather than having to hard-code them into the source-code.

**Comment by rfjakob** [comment]
`--prefer` / `--avoid REGEX` have been added in https://github.com/rfjakob/earlyoom/commit/d0bc5e00921ff43bc265ee31728596ef0b8360e4 and will be in the upcoming v1.0 release.
