### ISSUE TITLE
Earlyoom defaults discussion

### ISSUE THREAD

**Issue by birdie-github** [rfjakob/earlyoom#181]
By default `-m` is set to `10%` which looks excessive on machines with a lot of RAM, e.g. over `32GB`. Right now my PC is rocking `64GB` of RAM which means earlyoom will kick in as soon as free RAM goes below `3.2GB` which is a huge number. Imagine a server with `256GB` of RAM - earlyoom will start killing processes when free RAM goes below `12.8GB` which is insane.

Fedora developers have enabled these defaults which look much better and saner: `-m 4 -M 409600` - this will work both for devices with a lot of RAM and relatively little RAM.

***************

~~I really doubt we need `-r` to be enabled by default. Especially the default single second which looks absolutely excessive. It's probably OK for the developers but surely not for end users.~~

**Comment by hakavlad** [comment]
>Especially the default single second

Default is 3600, see https://github.com/rfjakob/earlyoom/blob/master/earlyoom.default

**Comment by birdie-github** [comment]
From `man earlyoom`:

```
   -r INTERVAL
       Time between printing periodic memory reports, in seconds (default 1.0). 
       A memory report looks like this:
```

**Comment by rfjakob** [comment]
Hi, I think there are two cases how earlyoom is run

1) Manually from the command line
2) As a service

Why would people want to run it manually (1)? Because they want see how it works and what it does. That's why the default is 1 second.

But if they run it as a service (2), the output should not clutter the log. That's why `earlyoom.default`, the config file for `earlyoom.service` sets `-r 3600`.

**Comment by Baltix** [comment]
@rfjakob Why you closed this issue? @birdie-github asked for -m defaults, now is set to 10% which looks really excessive on machines with a lot of RAM, e.g. over 32GB
Why don't set like in Fedora Workstation: -m 4 -M 409600 - this look much better and saner, will work both for devices with a lot of RAM and relatively little RAM.

**Comment by rfjakob** [comment]
Because i disagree with what fedora does. Reserving 3GB for cache on a 32GB machine looks reasonable to me.

**Comment by birdie-github** [comment]
> Because i disagree with what fedora does. Reserving 3GB for cache on a 32GB machine looks reasonable to me.

Workstations may easily have 64-128GB of RAM.
Servers may easily have up to terabytes of RAM.

Using 10% as a universal lower threshold for killing processes seems a little bit excessive but it's just my POV.

**Comment by hakavlad** [comment]
In any case admin can change defaults.
