### ISSUE TITLE
parse_meminfo() does not handle short reads

### ISSUE THREAD

**Issue by nh2** [rfjakob/earlyoom#189]
https://github.com/rfjakob/earlyoom/blob/924f7b2f88dcfaca6d7403ec84890ef104da0e02/meminfo.c#L79-L82

From `man 3 fread`:

> On success, `fread()` and `fwrite()` return the number of items read or written. This number equals the number of bytes transferred only when size is 1. If an error occurs, or the end of the file is reached, the return value is a short item count (or zero).

There are various ways how a read syscall (see `man 2 read`) can be interrupted, e.g. due to signal delivery, and technically short reads can happen for any reason.

There are 2 common ways to handle short reads:

* Repeat reading until all expected contents have been read (e.g. using `feof()`, see same man page, or using `read()` directly), this is the standard way and usually most correct.
* Notice the short read, and abort/warn as appropriate.

Currently earlyoom does not handle short reads at all; it continues with the subsequent logic.

**Comment by nh2** [comment]
I'll make a PR for it.

**Comment by rfjakob** [comment]
Hi, thanks for the PR, I see it fixes some obvious bugs, thanks!

But I'm not sure if `fread` can ever return incomplete data. This can happen with raw `read`, but I think `fread` has it's own retry loop.

**Comment by nh2** [comment]
> I think `fread` has it's own retry loop.

I think that is true, and https://stackoverflow.com/questions/53452824/read-fread-partial-reads/53453140#53453140 also says

> The `fread` function blocks until it's read as many bytes as were requested, until it's reached the end of the file, or until an error occurs. It works by calling `read` in a loop.

which was commented on by the author of musl libc so it is probably correct.

However, according to that answer, the [POSIX spec](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fread.html) saying

> _fread()_ shall return the number of elements successfully read which is less than _nitems_ only if a read error or end-of-file is encountered

and the quote from the man page that says

> If an error occurs, or the end of the file is reached, the return value is a short item count (or zero).

it still seems possible to me that short reads can occur as per specs (namely, if an error occurs), and that the quoted code should consequently at least check `feof()`, even if it doesn't implement retrying itself (that is, the point "Notice the short read, and abort/warn as appropriate" above).

Do you agree?

**Comment by rfjakob** [comment]
Yes, checking `feof()` sounds good. I like that i catches the case of the buffer being too small.

**Comment by nh2** [comment]
@rfjakob Sorry, I meant `ferror()`.

**Comment by nh2** [comment]
Done in PR #192

**Comment by krissada983** [comment]
yakin ga bisa dibuka om?
✓sudahkah paham mendownload melalui Adfly?
✓sudahkah menonton video dengan jujur tanpa di skip☺️🙏?
✓sudahkan men extrack file dengan 1 file 2x password?
✓sudahkah men subscribe channels DRIVER ONLINE ALL d.o.a...?
✓sudahkah berbudaya membaca sebelum bertanya???

jika ini sudah dilakukan dan masih blum bisa mohon japri dan kirim bukti screenshoot tidak bisanya dibagian manah. nti dibantu.

✓pastikan semua sudah dilakukan. jika bukti screen ter indikasi ada yg belum dilakukan maka hanyandi read☺️🙏

+62 menuju smart....
semangat☺️🙏...
