### ISSUE TITLE
[FR] - Get notification when killing a process

### ISSUE THREAD

**Issue by hnykda** [rfjakob/earlyoom#19]
Hello,

I really like `earlyoom`, but sometimes it kills some of my processes without no notification. I have to wonder what happened. e.g. `python` program is just silently ended without no information about being killed or whatsoever. 

It would be really awesome if we could have some event on which notification would be triggered, e.g. the most simple one like:

```
notify-send 'EarlyOOM' 'Process {$name}:{$PID} killed' --icon=dialog-information
```

right now it could be implemented as a workaround, when watching stdout of systemd unit. But some nicer solution would be great.

**Comment by kernc** [comment]
Also `wall(1)` notification would be nice.

**Comment by oualiaek** [comment]
Hello,

Add the following code in kill.c file  after each fprintf(...) to get a notification on ubuntu, you may change the output for each situation.

> char buffer[200];
> snprintf(buffer, 200, "/usr/bin/notify-send \'EarlyOOM\' \'Killing process %d %s\'", victim_pid, name);
> system(buffer);

Cheers

**Comment by bugmenot2** [comment]
It would be also handy if earlyoom reported memory consumption of the victim at the moment of killing (if not always then on `-d` option at least). When running experimental software in limited memory environment, it can be hard to tell whether a program really ate memory or there were just too many programs running.

**Comment by rfjakob** [comment]
Added in https://github.com/rfjakob/earlyoom/commit/c26a232fbef72b8dd4dc59376c690d87a66ba9fb !
