### ISSUE TITLE
Correct PID but incorrect victim name

### ISSUE THREAD

**Issue by PLPeeters** [rfjakob/earlyoom#194]
We're using EarlyOOM on a JupyterLab (1.X) instance. I created a notebook where I just created some huge strings to eat some memory and when it got killed, the correct PID was logged, but the process name was wrong.

Before creating the last string that generates the OOM, I checked htop:

![Screenshot 2020-04-30 at 13 45 59](https://user-images.githubusercontent.com/3260909/80707614-8bc2c800-8aea-11ea-89f1-7e6d2b3a94c4.png)

EarlyOOM logged this:

```
Apr 30 11:46:14 <hostname_removed> earlyoom[1000]: Out of memory! avail: 82 MiB < min: 230 MiB
Apr 30 11:46:14 <hostname_removed> earlyoom[1000]: Killing process 7981 htop
```

So the PID is correct, but the name isn't (also, htop was still running after that, so it clearly killed the right PID).

I then generated OOMs in a JupyterLab Terminal with `tail /dev/zero` and in a Python shell in said terminal to see if the JupyterHub environment could be the issue in itself, and there the logs are fine (as expected after reading through #65).

**Comment by hakavlad** [comment]
What version are you using?

**Comment by hakavlad** [comment]
What version do you use?

**Comment by PLPeeters** [comment]
Interesting, I was assuming it was the last one but apparently it's version 1.0, despite being freshly installed via `apt` on Ubuntu 18.04... Is that expected behaviour?

**Comment by hakavlad** [comment]
Ubuntu offers an outdated version.
