### ISSUE TITLE
Kill process with largest swap usage

### ISSUE THREAD

**Issue by simopal6** [rfjakob/earlyoom#197]
It seems that the current default is to kill the process with largest memory usage (which I think sums RAM and swap).

Is it possible to kill a process based only on swap usage?

**Comment by hakavlad** [comment]
Why do you need it? What's wrong with killing by oom_score?

**Comment by simopal6** [comment]
I would like to kill the process that causes swapping to happen, which is not necessarily the largest process running. E.g., i have 8 GB memory (let's ignore OS processes and stuff), I start process A which takes 6 GB (and is actively running), then I start process B which takes 3 GB, 2 of which fit into memory and 1 goes into swap. I wouldn't want to kill process A, since it's process B's "fault" that swapping occurred, so I would like to kill B.

However, now that I think about it, I'm not sure that the kernel will swap B's data, it may also swap A's, so I doubt that my reasoning is correct...

**Comment by hakavlad** [comment]
>I wouldn't want to kill process A

You would use `--prefer`/`--avoid` option to prefer/avoid process to be killed.

Usually old unused processes are swapped-out first.
For example:
```
oom_score oom_score_adj  UID   PID Name            VmRSS   VmSwap
--------- ------------- ---- ----- --------------- ------- --------
      462             0 1000 14615 python3          7955 M    216 M 
       29             0 1000  7768 firefox-esr        91 M    428 M 
       16             0 1000 11483 Web Content        36 M    255 M 
        5             0    0   939 Xorg               66 M     27 M 
        5             0 1000  7867 Web Content        27 M     62 M 
        5             0 1000 14181 Web Content        55 M     49 M 
        5             0 1000 14214 Web Content        31 M     68 M 
        4             0 1000  7925 WebExtensions      13 M     74 M 
        4             0 1000 10726 Web Content        22 M     49 M 
        2             0 1000 11590 Web Content         7 M     41 M 
```
In this case: I worked in browser, and i started python script that consumed memory. In the end old-running processes was swapped-out. In this case firefox (innocent victim) will be killed first if we will find victim by VmSwap.

**Comment by rfjakob** [comment]
Hi, thanks for the idea, but I agree with @hakavlad . I don't think that's good feature to have as it will be unpredictable what happens.
