### ISSUE TITLE
mv man(1) man(8)

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#198]
```
Only select manuals from the specified section. The currently available sections are:

1 General commands (tools and utilities).
...
8 System maintenance and operation commands.
```
https://www.mankier.com/1/man.mandoc

earlyoom is System maintenance and operation tool. That's why man page should be located at `/usr/share/man/man8/`.

For example, other System maintenance and operation commands:
https://linux.die.net/man/8/init
https://linux.die.net/man/8/rsyslogd

**Comment by rfjakob** [comment]
I agree that section 8 looks like a good fit. But there's a lot of stuff in section 1 like https://manned.org/systemd.1 , so it looks like it does not really matter.

Given that Debian already has the man page in section 1 ( https://packages.debian.org/buster/earlyoom ) I want to keep it as-is.
