### ISSUE TITLE
`dbus-send` become zombies

### ISSUE THREAD

**Issue by oxalica** [rfjakob/earlyoom#200]
When dbus notification is enabled (`-n`), it fork-exec `dbus-send` but never `wait` or handles `SIGCHLD`, making child processes zombies forever.

<img width="262" alt="Screenshot_20200530_225506" src="https://user-images.githubusercontent.com/14816024/83331528-857e6200-a2c9-11ea-9339-e2ad0fa17543.png">

**Comment by rfjakob** [comment]
Fixed via https://github.com/rfjakob/earlyoom/commit/321914127d7411c702b61ab80588bd2e06d7f148 thanks!

**Comment by leahneukirchen** [comment]
This code is not sufficient, there could be only one SIGCHLD but multiple children died.
