### ISSUE TITLE
support for checking multiple swap partitions

### ISSUE THREAD

**Issue by cmurf** [rfjakob/earlyoom#202]
Hi, I'm not certain whether the current "swap percentage" check is based on checking only one swap device? Or total swap? The kernel supports up to 32 swap devices.

In Fedora 33 feature proposal
https://fedoraproject.org/wiki/Changes/SwapOnZRAM

It's possible (not absolutely decided yet) that on upgrades there could be two swaps: the "legacy" swap-on-disk, and also swap-on-zram. So the question is whether it already ensures there will only be oom kill if the combine swaps become full; or at least that the oom behavior is reasonable rather than killing something off just because only one of the swaps is full.

**Comment by rfjakob** [comment]
Hi, it's based on `SwapTotal` and `SwapFree` as reported in /proc/meminfo. That's the sum of all swap  devices and the same as `free` reports.

**Comment by cmurf** [comment]
Awesome. Thanks.
