### ISSUE TITLE
Shouldn't earlyoom take pagecaches into account?

### ISSUE THREAD

**Issue by bjourne** [rfjakob/earlyoom#208]
Earlyoom kills processes in the following situation:
```
$ head /proc/meminfo
MemTotal:        8051520 kB
MemFree:          222960 kB
MemAvailable:     367088 kB
Buffers:           26116 kB
Cached:          5718484 kB
SwapCached:            0 kB
Active:          6052532 kB
Inactive:         896208 kB
Active(anon):    5907232 kB
Inactive(anon):   713992 kB
```
That seems a little to eager because there is lots of memory available in the page caches. Is there some knob you can tune to make it not kill processes if you have lots of memory in page caches?

**Comment by bjourne** [comment]
Same problem https://serverfault.com/questions/940196/why-is-memavailable-a-lot-less-than-memfreebufferscached

**Comment by rfjakob** [comment]
Interesting. MemAvailable *should already* take the page cache into account. The serverfault question seems to be spot-on. Do you use virtualbox?

**Comment by hakavlad** [comment]
@bjourne Could you provide full meminfo output?

**Comment by hakavlad** [comment]
>The part of Cached which is not freeable as page cache (sigh), is counted as Shmem in /proc/meminfo.

https://serverfault.com/a/972296

Shmem (tmpfs content) is part of cache.

For example:
```
$ cat /proc/meminfo
MemTotal:       10016616 kB
MemFree:          481160 kB
MemAvailable:     323136 kB   <-- 300 MiB mem available
Buffers:           62476 kB
Cached:          5919060 kB   <--- 5.9 GiB cache
SwapCached:            0 kB
Active:          3110872 kB
Inactive:        5702508 kB
Active(anon):    2833840 kB
Inactive(anon):  5394368 kB
Active(file):     277032 kB
Inactive(file):   308140 kB
Unevictable:       80644 kB
Mlocked:             432 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               180 kB
Writeback:             0 kB
AnonPages:       2912584 kB
Mapped:           428200 kB
Shmem:           5396348 kB   <---- 5 GiB tmpfs is part of cache
```

>Is there some knob you can tune to make it not kill processes if you have lots of memory in page caches?

System will hang if MemAvailable -> 0 in any case, even with large cache size.

**Comment by hakavlad** [comment]
How to reproduce: create large files in tmpfs.

**Comment by hakavlad** [comment]
What happens if nothing is done? The system will hang even with large cache size.

**Comment by bjourne** [comment]
How frustrating that the field is called cache but includes allocations that are persistent. I'll see if I can reproduce the situation I saw earlier today. I had to reboot the computer so the page cache hasn't filled up yet.

**Comment by rfjakob** [comment]
Good point, hakavlad. Maybe it's just files on tmpfs. @bjourne can you check
```
df -Th
```
if you have a lot of disk space used on tmpfs?

**Comment by bjourne** [comment]
Thanks for the tip! Now I've been able to reproduce the problem and it indeed seems like tmpfs is and was the problem:

```
ilesystem     Type      Size  Used Avail Use% Mounted on
dev            devtmpfs  3.9G     0  3.9G   0% /dev
run            tmpfs     3.9G  1.3M  3.9G   1% /run
/dev/sda6      ext4      129G   93G   30G  76% /
tmpfs          tmpfs     3.9G  356M  3.5G  10% /dev/shm
tmpfs          tmpfs     3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs          tmpfs     3.9G  2.3G  1.7G  58% /tmp
/dev/sda3      fuseblk    96G   87G  8.7G  91% /mnt/windows
/dev/sda1      vfat       96M   81M   16M  84% /boot
tmpfs          tmpfs     787M   36K  787M   1% /run/user/1000
```
