### ISSUE TITLE
earlyoom can kill a process with oom_score_adj=-1000

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#210]
>v0.9: If oom_score of all processes is 0, use VmRss to find a victim.

earlyoom can kill a process with oom_score_adj=-1000 if the badness of all processes is zero. Is it true? Is it OK?

**Comment by rfjakob** [comment]
Yes that could happen. Unlikely, but still. I think I will add a check for that.

**Comment by hakavlad** [comment]
Would you make a release after closing this issue?

Suggestion: skip processes with oom_score_adj <= -900 when selecting a victim.
