### ISSUE TITLE
The options `-p`, `--prefer`, and `--avoid`, are locked out by the systemd service's AmbientCapabilities - missing `CAP_SYS_NICE CAP_SYS_RESOURCE`.

### ISSUE THREAD

**Issue by SvobodaJakub** [rfjakob/earlyoom#215]
The systemd service has only `AmbientCapabilities=CAP_KILL CAP_IPC_LOCK`.

Missing `CAP_SYS_NICE` causes systemctl status earlyoom.service to report `Could not set priority: Permission denied. Continuing anyway`.

Missing `CAP_SYS_RESOURCE` causes systemctl status earlyoom.service to report `Could not set oom_score_adj: Permission denied. Continuing anyway`.

The options `-p`, `--prefer`, and `--avoid` do not work as documented.

I propose to change the line to `AmbientCapabilities=CAP_KILL CAP_IPC_LOCK CAP_SYS_NICE CAP_SYS_RESOURCE`.

Thanks!

**Comment by rfjakob** [comment]
I think instead of using `-p`, this should be done using `OOMScoreAdjust=` and `Nice=` in systemd:

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#OOMScoreAdjust=
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Nice=

You can add these by running
```
sudo systemctl edit earlyoom
```

**Comment by SvobodaJakub** [comment]
Hi, sorry for replying so late.

Right, using systemd functionality when run under systemd is more robust and better.

My aim is to make the specific issue of `-p` not working as expected under the default systemd service easier to understand, or to make it work. Do you think it might be a good idea if I submit a PR with a modified man page explaining this? Something like:

> `-p` doesn't work with the default systemd service. Instead, enter the following three lines into `sudo systemctl edit earlyoom`:
>
> `[Service]`
> `OOMScoreAdjust=-100`
> `Nice=-20`


In other words, when using earlyoom, I see this bug:

**Expected behavior**: `-p` works as documented.
**Actual behavior**: `-p` doesn't work if started through systemd.
**Possible resolution**: Document that `-p` intentionally doesn't work in the default systemd service. Document how to get it working.

Thanks!

**Comment by rfjakob** [comment]
Yes added that to the docs sounds good!
