### ISSUE TITLE
Ubuntu 20.04 package still on v1.3?

### ISSUE THREAD

**Issue by konstantinua00** [rfjakob/earlyoom#223]
Warning: I'm noob, I don't know much how to use linux  
I'm on Ubuntu, recently updated from 18.04 to 20.04.  

When I do `sudo apt install earlyoom`, `earlyoom` appears in processes list in System Monitor.  
If I do `earlyoom` in terminal next, first line it reports is `earlyoom v1.3`  
There's also no `earlyoom` file gets created in `/etc/default`, so problem might be on my side... But I have no idea how to fix it or even what to start looking for

Thank you for your effort

**Comment by lethosor** [comment]
Ubuntu 20.04 does indeed distribute earlyoom 1.3. Ubuntu 20.10 distributes 1.6 (but not 1.6.2, as far as I can tell). You can look up the versions of packages available in different versions of Ubuntu [here](https://packages.ubuntu.com/). For example, for earlyoom: https://packages.ubuntu.com/search?keywords=earlyoom&searchon=names&suite=all&section=all

Once an Ubuntu release is published, the packages it includes are rarely updated except for security reasons, although this might differ a bit for "point" releases for LTS versions (e.g. 20.04.1). A detailed policy on the matter can be found here: https://wiki.ubuntu.com/StableReleaseUpdates

If you need a newer version, I would recommend compiling from source as [detailed in the readme](https://github.com/rfjakob/earlyoom#download-and-compile). As long as you have git and gcc installed, it should be fairly quick.

**Comment by rfjakob** [comment]
Thanks @lethosor , that's right. Nothing I can do about the Ubuntu package, unfortunately.
