### ISSUE TITLE
Irritating choice of newest Firefox window / Feature proposal - prefer oldest process

### ISSUE THREAD

**Issue by mikedlr** [rfjakob/earlyoom#224]
I've noticed that it quite often kills the window I have just opened.  

Observed behaviour:
* earlyoom kills FireFox windows that have just been opened
Desired behaviour :
* earlyoom kills FireFox windows that have largest memory use and have been running for a long timel.

Log - the kill is at 15:10:12

   Oct 09 10:13:27 Catherine earlyoom[1307]: mem avail:  2044 of 15482 MiB (13.21%), swap free:  183 of  975 MiB (18.84%)
   Oct 09 10:46:19 Catherine earlyoom[1307]: mem avail:  1430 of 15482 MiB ( 9.24%), swap free:   95 of  975 MiB ( 9.79%)
   Oct 09 10:46:19 Catherine earlyoom[1307]: low memory! at or below SIGTERM limits: mem 10.00%, swap 10.00%
   Oct 09 10:46:19 Catherine earlyoom[1307]: sending SIGTERM to process 25850 uid 1000 "Web Content": badness 397, VmRSS 1596 MiB
   Oct 09 10:46:21 Catherine earlyoom[1307]: process exited after 2.8 seconds
   Oct 09 15:10:12 Catherine earlyoom[1307]: mem avail:  1507 of 15482 MiB ( 9.74%), swap free:   43 of  975 MiB ( 4.42%)
   Oct 09 15:10:12 Catherine earlyoom[1307]: low memory! at or below SIGTERM limits: mem 10.00%, swap 10.00%
   Oct 09 15:10:12 Catherine earlyoom[1307]: sending SIGTERM to process 23276 uid 1000 "Web Content": badness 393, VmRSS 1536 MiB
   Oct 09 15:10:15 Catherine earlyoom[1307]: process exited after 3.0 seconds
   Oct 09 15:12:08 Catherine earlyoom[1307]: mem avail:  3196 of 15482 MiB (20.64%), swap free:    0 of  975 MiB ( 0.00%)
   Oct 09 15:43:22 Catherine earlyoom[1307]: mem avail:  1507 of 15482 MiB ( 9.74%), swap free:    0 of  975 MiB ( 0.00%)
   Oct 09 15:43:22 Catherine earlyoom[1307]: low memory! at or below SIGTERM limits: mem 10.00%, swap 10.00%
   Oct 09 15:43:22 Catherine earlyoom[1307]: sending SIGTERM to process 21444 uid 1000 "Web Content": badness 406, VmRSS 1746 MiB
   Oct 09 15:43:25 Catherine earlyoom[1307]: process exited after 2.8 seconds

I currently run it like

    /usr/local/bin/earlyoom -r 3600 --avoid (^|/)(init|X|sshd)$ --prefer (^|/)Web Content$

It seems a little aggressive in killing `Web Content` processes, but otherwise fine.  However, 
* it would be better if the `Web Content` process which was killed was the oldest one rather than newest.
* it might be better to have a little hysteresis - if we go below 10%, kill repeatedly until we get above 20%??  This makes it less likely that a new process would be killed immediately.

I've started using and experimenting with earlyoom - it has as more or less solved my problems with Firefox. Most importantly it means I don't lose system interactivity so I can debug what's going wrong.  So I'd just like to quickly say _hanks everybody_.

**Comment by joeytwiddle** [comment]
Some similar requests in #226

**Comment by rfjakob** [comment]
I'm sorry, I have to keep earlyoom as minimal as possible so I can continue to maintain it. Maybe take a look at https://github.com/hakavlad/nohang ?
