### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#225]
@rfjakob Could you make a release, please?

https://github.com/rfjakob/earlyoom/commit/e34e0fcec5d9f60eb19a48a3ec2bab175818fdd8 is important.

See also https://bugzilla.redhat.com/show_bug.cgi?id=1887113

**Comment by rfjakob** [comment]
Done, https://github.com/rfjakob/earlyoom/releases/tag/v1.6.2
