### ISSUE TITLE
Suggestion: 1. somehow try to avoid killing the active focused window 2. avoid killing anything started less than X minutes ago

### ISSUE THREAD

**Issue by ell1e** [rfjakob/earlyoom#226]
I just got this experience of somebody trying earloom:

> [I tried OOM behavior] without cgroups or oom: system hangs very fast, besically as soon as I open 5 tabs in Firefox. [Then I tried limiting] with cgroups: system gets slow, I have some time to react and close, say, Fractal, or close some tabs. [And with earlyoom for] oom: "argh my window got closed for the 5th time!" because my window (fractal/firefox) is the ram-hungry one.

This sounds like an unfortunate experience, and I've thought about this before given browsers are a great target to shoot down *except* when I'm actually currently browsing.

I can see two ways, which ideally both would be worth implementing together, to improve this:

1. collaborate with desktop compositor authors to avoid killing the active, focused window in a graphical environment, e.g. by providing some sort of shared mechanism (via d-bus or something?) to query what the process parent is that the user is currently looking at right now so that it can be avoided as a kill target

2. avoid killing anything started less than X minutes ago if possible, such that there is no "I can't even launch this since it is shot down immediately!" situation. I think a good default would be around 60 seconds at least

This is more of an issue on memory tight systems like e.g. raspberry pi or the PinePhone (which has 2GB RAM in some editions), where otherwise it might be impossible to start a process that otherwise on its own would just about "fit" the budget, but becomes the obvious preferable kill target after launch and in practice is therefore possibly unlaunchable with earlyoom unless I manually stop everything else first - which I feel like is an unfortunate outcome. And these memory tight systems would also benefit most from earlyoom in general for the end user experience, at least if such issues could be largely avoided. So I feel like this really would be worth looking into at some point.

**Comment by joeytwiddle** [comment]
I achieved this by:

1. Giving a worse score to browser tabs, but not to the browser core process (using regexps)
2. Giving a worse score to processes which have been running for longer
3. Reducing the contribution that memory consumption adds to the score (undoing some of the system's scoring) because sometimes the current tab temporarily uses a lot of memory

This has been working fairly well. I run my fork on my desktop machines. But it's a bit behind master now.

https://github.com/rfjakob/earlyoom/issues/8#issuecomment-155708419

**Comment by ell1e** [comment]
Yes, that sounds useful. Ideally at least your suggestions would all be integrated, *and* then additionally one that rules out the one the UI currently has active on top of things for even better expected behavior. This is also what Android does at least in older versions (that wouldn't kill background things as aggressively as new ones), which is essentially leave things running until overall memory gets tight and then one by one terminate what the user is *not* currently looking at.

**Comment by rfjakob** [comment]
I agree that these are all good ideas. However, this will need a lot of tweaking, tuning, experimenting to find good settings, also probably a lot of extra complexity in the C code. The goal of earlyoom is to be stupid, simple, and reliable, also for the reason that I cannot maintain it properly if it gets too complex.

Maybe take a look at https://github.com/hakavlad/nohang ? It is written in Python, easier to extend, and offers a lot of configuration options.

**Comment by ell1e** [comment]
@rfjakob could you at least consider the preferably not killing anything that just launched change? This seriously makes earlyoom borderline unusable on really low memory mobile devices like the 2GB PinePhone when something just started often ends up the thing shot down, which is also coincidentally exactly where it would be preferable to run a leaner C-based daemon that likely reacts faster than a Python one.

**Comment by rfjakob** [comment]
Do you know where to see when a process was launched?

**Comment by ell1e** [comment]
It seems to be somewhat complicated to get the exact launch time, sadly.

I can think of three approaches of making it happen:

1. Scan all processes in a fixed interval, and just store a timestamp of when they are first seen inside earlyoom until they disappear (very portable, but of course very coarse. Might be enough however for a vague "has been launched in the last 2-3 minutes" criteria which is likely enough for a good result)

2. Try to parse `/proc/$PID/stats`'s hard to process "jiffies" time: https://stackoverflow.com/questions/5828753/start-time-of-a-process-on-linux (not very portable, I would assume)

3. Use `ps` which apparently has the very complicated code for an exact time baked in: https://unix.stackexchange.com/questions/7870/how-to-check-how-long-a-process-has-been-running

I personally would think 1. might be the best one for relatively simple, portable code.

**Comment by hakavlad** [comment]
>Do you know where to see when a process was launched?

In Python
```
starttime = float(readline('/proc/' + pid + '/stat').rpartition(')')[2].split(' ')[20]) /  SC_CLK_TCK

uptime = float(rline1('/proc/uptime').split(' ')[0])

lifetime = uptime - starttime
```

**Comment by ell1e** [comment]
I would highly recommend reading the links I mentioned, in particular determining `SC_CLK_TCK` (the jiffies scaler, essentially) reliably is apparently hard for some reason. But otherwise, this does correspond to solution 2.

**Comment by hakavlad** [comment]
>It seems to be somewhat complicated to get the exact launch time

It's easy.

>hard for some reason

`clockTicks = sysconf(_SC_CLK_TCK)` - what is the problem?

**Comment by rfjakob** [comment]
Thanks! I don't like (1) very much because it means earlyoom has to keep a table of all processes in memory

**Comment by ell1e** [comment]
> clockTicks = sysconf(_SC_CLK_TCK) - what is the problem?

I mean, I linked it all above. The problem is that  this value is hardcoded into the libc and therefore apparently often wrong.

**Comment by rfjakob** [comment]
libc vs kernel mismatch?

**Comment by ell1e** [comment]
Here is the `ps` explanation & workaround code: https://gitlab.com/procps-ng/procps/blob/master/proc/sysinfo.c#L159

**Comment by rfjakob** [comment]
Wow, that's horrifying. What about looking at the timestamp of /proc/PID, though ( https://unix.stackexchange.com/a/335688/45823 )?

**Comment by ell1e** [comment]
Yeah that might work. Maybe if you want it to be cross-platform compatible for BSD etc, how about tracking the PIDs clumsily like I suggested (at the expense of the ~16KiB that would take) as a fallback for when stat on /proc/PID is not available or failing for some reason? I feel like that could turn out to be a sufficiently robust solution.

**Comment by ell1e** [comment]
Yeah, maybe. I'm thinking: usually you'd score all processes anyway for comparison, wouldn't you? So you could just loop over it once collecting the time for all of them at that point once. But if that doesn't work with your code structure, a simple modulo-based hash probably would do fine rather than a more complicated hash function. But yes, it would definitely be slightly more involved to handle than just calling stat only.

So for Linux-specific stat() alone should be fine, I assume. (Not that I know more than you on this, the StackOverflow response obviously doesn't mention this being unavailable on some linux kernels for some reason so I *guess* it is always available, but no idea.)

**Comment by jayenashar** [comment]
> For the table you propose you'd need some kind of hash table, and this seems like a huge headache in C

I think you could do it with an array if you know the max number of PIDs.  I was thinking it could be done like this:

```c
const int NUM_MAX_PIDS = 65536;
// start_times[i] = (epoch time (seconds since 1970) - start time of earlyoom) >> 16
unsigned short *start_times = malloc(NUM_MAX_PIDS * sizeof(short));
```

**Comment by ell1e** [comment]
16bit int, for time values? What for PCs that run for a long time? I think this is the wrong place to optimize, it's better to use 64bit for timestamps or at least 32bit if a relative one. So yes, would still require hash buckets then, but no complicated hash function at least. Also, your suggestion would still use up around 2MiB at least even with 16bit ints, so likely somewhat more in any case.

**Comment by jayenashar** [comment]
it's going to be hard to cater for embedded systems and servers.

64k PIDs * 2 bytes/PID = 128k

yes i'd prefer to use more bytes for the time.  it was just an idea if you wanted to use less bytes, and not complicate things with a hash function.

**Comment by joeytwiddle** [comment]
> ```
> starttime = float(readline('/proc/' + pid + '/stat').rpartition(')')[2].split(' ')[20]) /  SC_CLK_TCK
> ```

If you take this approach, you may like to wrap it in a try catch or other suitable guard. I found with my C implementation, by the time this code ran, sometimes the process had ended all by itself, so the file was missing.

**Comment by hakavlad** [comment]
Of course, I handle FileNotFoundError and ProcessLookupError in such cases.
