### ISSUE TITLE
Changes made in /etc/default/earlyoom doesn't reflect when earlyoom is executed

### ISSUE THREAD

**Issue by 1999shaswat** [rfjakob/earlyoom#229]
When i execute earlyoom in terminal, it shows default values. It doesnt reflect the changes made in the config file.
![Screenshot_20201124_163003](https://user-images.githubusercontent.com/43248642/100085700-5f99da80-2e72-11eb-8f45-ce59e5530967.png)

**Comment by hakavlad** [comment]
Options from /etc/default/earlyoom not passed to earlyoom when you run earlyoom from terminal.

These options passed to earlyoom when it  started as service.

**Comment by 1999shaswat** [comment]
Its there any way to check whether the settings loaded or not? Thanks for replying

**Comment by jayenashar** [comment]
i check like this:

```
jayen@eeyore:~$ ps -ef | grep early
root      1262     1  0 Nov18 ?        00:00:53 /usr/bin/earlyoom -r 60
```

**Comment by 1999shaswat** [comment]
Thanks. I'm closing the issue then. Okay?
