### ISSUE TITLE
earlyoom does not pick process with highest memory

### ISSUE THREAD

**Issue by SamDM** [rfjakob/earlyoom#230]
I have local k3s and docker server running, and for some reason earlyoom always tries to kill processes related to those services instead of the actual process that takes up most memory. For example if I start a python script that creates object that grows forever in a loop, it quickly rises to the top of my `htop` but it is not the process that gets killed, instead `metrics-server` gets killed.

```
sending SIGTERM to process 4173 uid 0 "metrics-server": badness 1001, VmRSS 31 MiB
kill failed: Operation not permitted
```
The things is `metric-server` is barely using any resources (at least according to `htop`). I tried putting `metrics-server` in the `--avoid` flag but then `earlyoom` tried to kill `entry`, which is a docker process. Putting `entry` in the avoid list as well, the next target is `nginx`, adding `nginx` it picks `coredns`. Even putting `--prefer "python"` doesn't make `earlyoom` target the python process.

I guess this is one of those things that only happens on few systems, so I'd like some pointers on how to debug this.

Cheers

**Comment by hakavlad** [comment]
>badness 1001

earlyoom tries to kill process with highest oom_score.

Run `oom-sort` script to check oom_score and oom_score_adj of all processes and sort processes by oom_score.

https://github.com/hakavlad/nohang/blob/master/src/oom-sort

Maybe metrics-server has high oom_score_adj.

**Comment by rfjakob** [comment]
So the "badness 1001" suggests that metrics-server increases its oom_score by +1000. The --avoid and --prefer options increase/decrease the oom_score by 300. So not enough to overcome the +1000.

What you can do though, is, to use the `-i` flag. Then earlyoom will try to ignore the +1000 that metrics-server gives itself.

**Comment by rfjakob** [comment]
PS: I did not know that badness can go over 1000!

**Comment by hakavlad** [comment]
It's since Linux 5.9 https://ibb.co/9N2c0pH https://ibb.co/xfD6Ty9 oom_score=666 by default, valid values: [0; 1332] instead of [0; 1000].

https://lore.kernel.org/linux-mm/20200709062603.18480-2-mhocko@kernel.org/

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9066e5cfb73cdbcdbb49e87999482ab615e9fc76 @rfjakob

**Comment by rfjakob** [comment]
Interesting. Same here on Fedora 33 now.

```
0 jakob@brikett:/$ uname -a
Linux brikett 5.9.13-200.fc33.x86_64 #1 SMP Tue Dec 8 15:42:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
0 jakob@brikett:/$ grep . /proc/*/oom_score
/proc/1007/oom_score:666
/proc/1016/oom_score:666
/proc/105/oom_score:0
[...]
```
