### ISSUE TITLE
Nice to have: new option to kill all processes with same name

### ISSUE THREAD

**Issue by 3DRaven** [rfjakob/earlyoom#235]
When earlyoom fairs kill for some process, need option that about killall processes with same name. As example kill all java processes in system, not only one largest by memory. Because it can be group of depend programs and kill one just corrupt another.

**Comment by hakavlad** [comment]
>killall processes with same name

```
##  8. Customize soft corrective actions

##  Run the command instead of sending a signal with at soft corrective action
##  if the victim's name or cgroup matches the regular expression.

@SOFT_ACTION_RE_NAME       ^java$        /// killall  $NAME
# $NAME will be replaced by victim's name if name matches ^java$ regex
```
https://github.com/hakavlad/nohang/blob/master/conf/nohang/nohang.conf.in

>it can be group of depend programs and kill one just corrupt another

Look at oomd. It kills only entire cgroup.
https://github.com/facebookincubator/oomd

**Comment by rfjakob** [comment]
Hard do to right, too risky, sorry
