### ISSUE TITLE
Optimize lack of MemAvailable

### ISSUE THREAD

**Issue by rowlap** [rfjakob/earlyoom#239]
As the code warns, kernels prior to 3.14 don't provide `MemAvailable` from /proc/meminfo. In this case, available_guesstimate provides a fallback.

My concern is, in the usual case of earlyoom polling for stats, every loop has to learn afresh that `MemAvailable` is missing.

Given that we already store a flag in `guesstimate_warned`, could this be used on subsequent polls to bypass `get_entry("MemAvailable")`?

I'm assuming that /proc/meminfo fields won't change during a run of the program.

(This request is based on code inspection, not profiling, so it's fine to close if it's not worth the cycles.)

**Comment by rfjakob** [comment]
I don't think this case is worth to optimize, as kernels older than 3.14 are disappearing slowly, and at some point we can remove the whole guesstimate logic

**Comment by rowlap** [comment]
Fair enough; I'd assumed that certain RHEL versions would be lacking `MemAvailable` due to kernel version, when actually it's been backported.
