### ISSUE TITLE
How to simulate a kill action?

### ISSUE THREAD

**Issue by ceremcem** [rfjakob/earlyoom#242]
I currently need to avoid from using https://github.com/rfjakob/systembus-notify, so I wanted to parse logs by myself. How can I trigger the exact actions when earlyoom kills a process? Should I create a memory hungry process for that?

**Comment by jayenashar** [comment]
that is how i did it.  with this bash command: `</dev/zero head -c 10000m | pv -L 1000m | tail`

**Comment by ceremcem** [comment]
I couldn't understand. Should I create a Bash script and place this code inside and run the script, so the script fills the memory when executed and `earlyoom` does what it actually does?

**Comment by ceremcem** [comment]
Can you please comment on your code? What does it do exactly?

**Comment by ceremcem** [comment]
Okay, I got it. It occupies lots of memory, so `earlyoom` does what it does. The most valid solution, thanks!

**Comment by rfjakob** [comment]
Easiest way I know:

tail /dev/zero
