### ISSUE TITLE
How to filter logs for killed processes?

### ISSUE THREAD

**Issue by ceremcem** [rfjakob/earlyoom#243]
We can get persistent logs by `sudo journalctl -u earlyoom`. How can I get logs of killed process? Should I search for a `killed` string, like `sudo journalctl -u earlyoom | grep -i killed`?

**Comment by jayenashar** [comment]
i am using this: `sudo journalctl -u earlyoom | grep sending`

for the most part, my processes exit cleanly and look like `process exited after 0.0 seconds`

**Comment by ceremcem** [comment]
@jayenashar Regarding to your other comment, `grep -i killing` solves the issue: 

```console
$ sudo journalctl -u earlyoom | grep -i killing
Feb 19 11:29:08 erik3 earlyoom[15368]: Killing process 'tail' with signal 15, pid: 24059, badness: 997, VmRSS: 4278 MiB
```
