### ISSUE TITLE
[Question] Is there a version for Windows?

### ISSUE THREAD

**Issue by stoufa** [rfjakob/earlyoom#245]
Awesome tool, I installed it on all of my Ubuntu systems. 😊  
I suppose that it is only meant for UNIX-based OSs since I can't see Windows in the list of supported systems.  
Windows, however, is the one that needs the most such a great tool.  
System freezes are more frequent and it goes without saying that many "blue screen" errors are caused by an out-of-memory error.  
So, is there a way to make this tool work on Windows? (a "How to make `earlyoom` work on Windows" guide for example)   ​
Otherwise, is it possible to support Windows systems?
Thanks in advance.

**Comment by rfjakob** [comment]
Hi! Sorry, no, Windows is very different here. I think it would be easier to start from scratch than to try and add Windows support to earlyoom.
