### ISSUE TITLE
Serious bug in get_entry_fatal

### ISSUE THREAD

**Issue by chneukirchen** [rfjakob/earlyoom#25]
In 0.10, get_entry_fatal does not return val in the good case.

This code only works by accident with `-O0`.

**Comment by rfjakob** [comment]
True, but this has been fixed in master since July 2016 ( https://github.com/rfjakob/earlyoom/commit/9251d25618946723eb8a829404ebf1a65d99dbb0 ).
I have released v0.11 right now that contains the fix.
