### ISSUE TITLE
"-n" option doesn't nothing at Plasma (openSUSE)

### ISSUE THREAD

**Issue by RafaelLinux** [rfjakob/earlyoom#250]
In openSUSE, earlyoom has this default config file:
`EARLYOOM_ARGS="-r 3 -m 6 -s 10 -n -p --avoid '(^|/)(systemd|Xorg|X|Xwayland|xdm|sddm|kdm|gdm|lightdm|plasmashell|kwin_wayland|kwin_x11|ssh|yast|yast2|y2controlcenter|zypper|rpm)$' --prefer '(^|/)(java|Web\ Content|firefox|chromium|chrome|opera|falkon|ffmpeg|vlc|mpv|akregator|thumbnail.so)$'"
`
However, Plasma doesn't notify nothing at all each time "earlyoom" makes his job.

Any suggestion?

**Comment by hakavlad** [comment]
what version do you use

**Comment by hakavlad** [comment]
```
1.6, 2020-04-11

    Replace old notify-send GUI notification logic with dbus-send / systembus-notify (#183) 
```
https://github.com/rfjakob/earlyoom/issues/183

You should enable this https://github.com/rfjakob/systembus-notify

**Comment by RafaelLinux** [comment]
```
Operating System: openSUSE Leap 15.2
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.81.0
Qt Version: 5.15.2
Kernel Version: 5.3.18-lp152.72-preempt
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
Memory: 15GiB of RAM
Graphics Processor: GeForce GTX 1050 Ti/PCIe/SSE2

 earlyoom-1.4-lp152.1.4
```


If I try 
`dbus-send --system --type=signal / net.nuetzlich.SystemNotifications.Notify "string:hello world"`

... no notification appear in Plasma. 

Moreover, "systembus-notify" doesn't exist in my system (even for install).

So earlyomm just works on my system, but doesn't notify when it triggers  ;)

**Comment by hakavlad** [comment]
With earlyoom 1.4 you need libnotify and special settings: 

look at https://github.com/rfjakob/earlyoom/tree/v1.4#notifications

**Comment by RafaelLinux** [comment]
If 

> With earlyoom 1.4 you need `libnotify` and special settings:
> 
> look at https://github.com/rfjakob/earlyoom/tree/v1.4#notifications

So, if I'm not wrong, I must edit /etc/sysconfig/earlyoom and add at the end of command , parameter : 
`-N 'sudo ............. bus notify-send' `
with appropriate values for my user and display

Is that?
