### ISSUE TITLE
Option -m does not work 

### ISSUE THREAD

**Issue by dazaykov** [rfjakob/earlyoom#255]
Hi.

Please tell me why the -m option may not work?

Debian 10 / Debian 11 / OpenSUSE 15.3 (earlyoom v1.2/v1.3/v1.4/v1.6)

\# earlyoom -m 50,49   
\# tail /dev/zero 
earlyoom does not kill the tail process, even when filling out the whole memory. It kills only when filling out swap.

\# earlyoom -s 50,49
\# tail /dev/zero 
earlyoom kills the tail process as expected when filling out swap by 50%

Ubuntu 20.4 (earlyoom v1.3)
earlyoom works correctly options -m and -s

Maybe in the Debian/OpenSUSE kernel something is missing?

**Comment by hakavlad** [comment]
Демон стреляет при превышении обоих порогов одновременно - порога памяти и порога свопа (10% дефолт для свопа.

А какой эффект нужен? 

Попробуй earlyoom -m 50,49 -s100 если интересует реакция только на размер доступной памяти вне зависимости от размера свободного свопа.

**Comment by hakavlad** [comment]
# earlyoom -m 50,49

В этом случае порог доступной памяти 50% и свопа 10% должны быть достигнуты одновременно - что и получаете на практике:
>It kills only when filling out swap.

**Comment by dazaykov** [comment]
Вот оно как))
Спасибо большое. Теперь работает.
-m 50,49 -s100

**Comment by hakavlad** [comment]
This issue may be closed.
