### ISSUE TITLE
Change the default of 10% to 5% as now most systems have 8GB and upwards. 

### ISSUE THREAD

**Issue by debian-user-france1** [rfjakob/earlyoom#258]
Change the default of 10% to 5% as now most systems have 8GB and upwards. 
I have set it up to 5% already on my 4GB RAM server. Is there any impact? It will kill at like 400MB remaining ram. I have scripts that consume so much that just 100MB is remaining (try to do hard dos attacks etc. or also some games might mess up and as we know they get killed before they would save all wich is very annoying for those.)

**Comment by rfjakob** [comment]
5% is pretty low and can lead to sluggish behavoir.

Note the the 10% of RAM are actually used for the page cache. In other words, the default of 10% reserves 10% of RAM for the page cache, which is actually pretty little!
