### ISSUE TITLE
[feature]  Instead of terminating try to trigger swapping

### ISSUE THREAD

**Issue by cipriancraciun** [rfjakob/earlyoom#278]
When the system is low on available RAM, but still has plenty of swap available, it would be nice to be able to trigger swapping of targeted processes (or swapping in general).

To be fair, I personally don't know if this is possible given today's Linux features, but I thought it wouldn't hurt to ask.  :)

I know that in theory having no RAM but plenty of swap should be transparent for applications, but for some reason at least Firefox fails (as it just kills itself) when there is few RAM available.  And I usually get into these situations because I rely heavily on `tmpfs` that should easily fit into swap.

**Comment by rfjakob** [comment]
Hi, sorry, no way I know of to trigger swapping.
