### ISSUE TITLE
support logging to separate file

### ISSUE THREAD

**Issue by gnowxilef** [rfjakob/earlyoom#29]
would be nice to be able to do this when running in daemon mode.

**Comment by rfjakob** [comment]
There is no daemon mode :)

**Comment by gnowxilef** [comment]
sorry, by daemon mode, i mean when running it using `init` or `systemd`.

**Comment by rfjakob** [comment]
systemd automatically logs all output, do you think we can do better?

**Comment by gnowxilef** [comment]
oh, good point. it might be nice to support logging to a separate file.

though i noticed that stdout is not being logged at all.

**Comment by rfjakob** [comment]
You should be able to get stdout logged by changing `StandardOutput=null` to `StandardOutput=syslog` in
(earlyoom.service)[https://github.com/rfjakob/earlyoom/blob/master/earlyoom.service#L2]

**Comment by rfjakob** [comment]
IMO logging works OK and can be configured through the .service file. I'll close this.
