### ISSUE TITLE
Document case of using no swap file

### ISSUE THREAD

**Issue by gorkemgoknar** [rfjakob/earlyoom#290]
From help and logs I understand it is a "and" for memory and swap, so in my case swap is always 0 , and earlyoom should trigger if memory is <=10% .

It may be better to document this case (if it is really like it) (it is a system where swap memory should not be used)

```
earlyoom v1.3
mem total: 2064060 MiB, swap total:    0 MiB
sending SIGTERM when mem <= 10 % and swap <= 10 %,
        SIGKILL when mem <=  5 % and swap <=  5 %
mem avail: 1875053 of 2064060 MiB (90 %), swap free:    0 of    0 MiB ( 0 %)

...
mem avail: 1875137 of 2064060 MiB (90 %), swap free:    0 of    0 MiB ( 0 %)
adaptive sleep time: 1000 ms
mem avail: 1875148 of 2064060 MiB (90 %), swap free:    0 of    0 MiB ( 0 %)
adaptive sleep time: 1000 ms

```

**Comment by rfjakob** [comment]
Yes that is correct. If you have no swap, it is considered as "0% free swap".

Do you have a suggestion as to where to document this?
