### ISSUE TITLE
Distribute Earlyoom via Container on Docker Swarm

### ISSUE THREAD

**Issue by kgncloud** [rfjakob/earlyoom#291]
Hi everybody,

We have a Servercluster that uses earlyoom to save us when things get messy with RAM. We searched and could not find a current maintained Container Version of earlyoom. At least (with no Go knowledge) we could not find what does earlyoom need (files, folders, permissions CAPs) to run. Distributing earlyoom as a container would be a) overkill for many b) Easy to rollout to new servers with only the need of kernel compatibility.

If somebody knows we would like to develop an Container Image for everybody to use :D

**Comment by rfjakob** [comment]
Hi, earlyoom is written in pure C, only the self-tests are in Go.

That being said, I'm not sure earlyoom can work within a container, as one container cannot see the processes from other containers, which defeats the purpose of earlyoom.

**Comment by fzyzcjy** [comment]
Hi, I wonder whether docker's pid=host configuration will work? Thanks
