### ISSUE TITLE
Earlyoom spams Journalctl and does not take LOGLEVEL=info

### ISSUE THREAD

**Issue by SysAdminShed** [rfjakob/earlyoom#298]
Hello,

We've been running earlyoom for a while now and it works great.

But it does spam journalctl with the status which doesn't help us in debuging other possible issue.

I've tried adding in /etc/default/earlyoom :

LOGLEVEL=info

But, no joy.

Is there any command to lower the verbose of earlyoom ?

Thanks in advance,

**Comment by rfjakob** [comment]
Hi, you probably want to set `-r 3600` or something
```
  -r INTERVAL               memory report interval in seconds (default 1), set
                            to 0 to disable completely
```

**Comment by SysAdminShed** [comment]
Hi,

Will setting the -r option to 3600, will reduce the efficiency of earlyoom to every 3600 second or only the report of memory status ?

Thanks in advance,

**Comment by rfjakob** [comment]
Only the report. It will react as quickly as before.
