### ISSUE TITLE
Options for users who want to use swap too

### ISSUE THREAD

**Issue by joeytwiddle** [rfjakob/earlyoom#3]
My use case differs slightly from yours.  I have a swap partition and I want to use it.

I want earlyoom to trigger when both the swap *and* the memory are nearly full.

I have been using this adapted version of earlyoom for a couple of weeks now, and it has served me well:  https://github.com/joeytwiddle/earlyoom/tree/wait_for_swap_to_fill

However it is not compatible with your use case!

I wonder if we should make the effort to combine both these requirements together, so that one package can serve both users with your requirements, and users with my requirements.

**Comment by kokizzu** [comment]
+1

**Comment by rparkhunovsky** [comment]
+1

**Comment by rfjakob** [comment]
Ok, I will implement this next week ;)

**Comment by rfjakob** [comment]
Done. It will now only kill processes if BOTH swap and ram are below 10%. Check out the updated readme at https://github.com/rfjakob/earlyoom , it explains the details.

**Comment by rparkhunovsky** [comment]
Is 10% a hardcode? Won't it be better to make it an option as that everyone could set it up on his own needs?

**Comment by xmikos** [comment]
I agree, there should be option for setting percents. If you have a lot of RAM, 10% can be too much.

**Comment by rfjakob** [comment]
Done. Check out the updated readme at https://github.com/rfjakob/earlyoom .
Best regards
