### ISSUE TITLE
Feature request: Add option to add up -m and -M minimal available memory

### ISSUE THREAD

**Issue by mars4science** [rfjakob/earlyoom#302]
If one includes the app in the distro, it is IMO useful to have universal `/etc/default/earlyoom`.

IMO it is more "universal" to have minimal memory at fixed amount+percentage. To keep the app backward compatible, please add option to add up `-m` and `-M` instead of choosing min of them. Thanks.

Edit: created pull request https://github.com/rfjakob/earlyoom/pull/305 with this feature. Please see documentation and code, review and merge.

**Comment by rfjakob** [comment]
See #305
