### ISSUE TITLE
Documentation: Explain connection between logging (badness) and readme explanation (oom_score), or change logging

### ISSUE THREAD

**Issue by 9SMTM6** [rfjakob/earlyoom#308]
A small documentation nitpick, where I'm not certain I have the knowledge to provide a proper fix myself:

The readme explains how its decided what process to kill: https://github.com/rfjakob/earlyoom#what-does-it-do, and references oom_score.

But when a process is killed, the log does not mention the oom_score of the killed processes, but only their VmRSS and badness.

After a bit of research, apparently [there is a connection between badness and oom_score](https://unix.stackexchange.com/questions/448871/what-is-the-relationship-between-oom-score-and-badness), but that is news for someone that's not an expert in these topics.

From the linked question, it seem that at any point in system time (so with static total number of pages), oom_scores and badness are proportional to each other.

I would suggest that either the log messages list the oom_score, or the README explains explains the connection between them.

If my understanding is correct, and you want to go the adjustment of README route, I can do a PR (if that makes things easier for you).

**Comment by rfjakob** [comment]
It should have been called "oom_score" everywhere. Fixed now, thanks!
