### ISSUE TITLE
Update documentation of --prefer and --avoid regex to note that the regex names are truncated to 15 characters

### ISSUE THREAD

**Issue by jorisvergeer** [rfjakob/earlyoom#311]
The documentation does not state that the names that are matched in the regex are truncated to 15 characters (16 including leading zero)

Earlyoom reads the name from /proc/XXXX/comm. This is the filename of the executable truncated to 15 characters. 

My application name is longer than this limit and thus wasn't killed by earlyoom while it should be killed preferably.

So, it would help future users to know this limit.

**Comment by tomjaguarpaw** [comment]
Wow, I was wondering why my regex didn't seem to work and luckily I came across this issue.

I agree, I think it would be really helpful to prominently call this out in the docs!

**Comment by hakavlad** [comment]
There is no problem if you take the names from the right source (from `ps -e` output).

**Comment by rfjakob** [comment]
I wonder what "ps -e" does for corrupt truncated utf8. Will test.

**Comment by tomjaguarpaw** [comment]
Thanks so much! And thank you for this very useful tool.
