### ISSUE TITLE
"make install" does not install man page

### ISSUE THREAD

**Issue by slicer69** [rfjakob/earlyoom#37]
When installing earlyoom, the program's manual page (earlyoom.1) is not installed. The attached, updated Makefile adds targets for "install-man" and "uninstall-man" which can be called directly or by an uninstall process.
[Makefile-earlyoom.txt](https://github.com/rfjakob/earlyoom/files/1486060/Makefile-earlyoom.txt)

**Comment by rfjakob** [comment]
Good find!

Could you create a fork of this repo, commit your change, and create a pull request?

**Comment by slicer69** [comment]
For something this small (changes one file), I just used GitHub's edit function and created the pull request from that. The pull request can be found here: https://github.com/rfjakob/earlyoom/pull/38

**Comment by rfjakob** [comment]
Has been fixed by https://github.com/rfjakob/earlyoom/commit/f89d46005ce8a0dccfd264d85384897afe19970d
