### ISSUE TITLE
Way to tell earlyoom not to kill some process (respect oom_score_adj)

### ISSUE THREAD

**Issue by xmikos** [rfjakob/earlyoom#4]
Hello,

I have some processes which can consume a lot of memory, but I don't want them to be killed by earlyoom. And I would also like to be able to set some processes to be preferably killed. So it would be really great if earlyoom could be told to respect _oom_score_adj_. I know there is problem for you with Chrome setting _oom_score_adj_ too high, but for me this is desired behavior (rather kill browser tab than some memory hungry - but important - process, computation, compilation, etc.). I know I can compile it with USE_KERNEL_OOM_KILLER, which would respect _oom_score_adj_, but I want to use userspace killing mechanism (I don't want to enable sysrq "f" trigger and I have also bad experience with kernel oom killer in general).

Ideally there should be some more fine grained setting, like list of processes (by name) for which earlyoom should ignore _oom_score_adj_ (this would solve your problem with Chrome) and setting how much should be _oom_score_adj_ taken into account when deciding what to kill. But for the start, even simple (preferably runtime) option to respect/don't respect _oom_score_adj_ would be enough.

**Comment by rfjakob** [comment]
Turns out triggering the kernel oom killer does not work at all anymore ( details at https://github.com/rfjakob/earlyoom/commit/f7e2cedce8e9605c688d0c6d7dc26b7e81817f02 ). So using the kernel oom killer is ruled out completely.

**Comment by xmikos** [comment]
@rfjakob So are you going to add option for userspace oom killer to respect _oom_score_adj_?

**Comment by rfjakob** [comment]
Yes, done. In fact, I have made it the default. Use `-i` if you want to ignore positive adjustments in oom_score_adj.
