### ISSUE TITLE
How to free up caches/buffers?

### ISSUE THREAD

**Issue by teneri66** [rfjakob/earlyoom#43]
earlyoom starts killing processes when just 10% of memory "available".
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            15G         12G        660M        883M        2,7G        2,0G
Swap:            0B          0B          0B
```
How to force system to free up more buffer/caches under certain conditions so that it frees more memory to become available?

**Comment by Nefelim4ag** [comment]
@teneri66, you want a bad thing, you want a duct tape...

https://www.kernel.org/doc/Documentation/filesystems/proc.txt
MemAvailable: An estimate of how much memory is available for starting new
              applications, without swapping. Calculated from MemFree,
              SReclaimable, the size of the file LRU lists, and the low
              watermarks in each zone.
              The estimate takes into account that the system needs some
              page cache to function well, and that not all reclaimable
              slab will be reclaimable, due to items being in use. The
              impact of those factors will vary from system to system.
MemAvailable, already get into account caches, you can make you WB MM cache more aggressive, but that also not really a good idea.

---
Only that you can do, it's drop caches by hand "in certain conditions", by sysctl + script,
But really with such big ram, you better change default % to something more real, like 2-3%.

**Comment by rfjakob** [comment]
Everything that **can** be freed is already included in the "available" number

**Comment by joeytwiddle** [comment]
Yeah you don't need to free caches. Caches will be automatically cleared if that memory is needed.

Clearing them can only make your machine slower.
