### ISSUE TITLE
Preferred processes

### ISSUE THREAD

**Issue by TomJohnZ** [rfjakob/earlyoom#46]
First, I wanted to thank you all for this great software. It's been quite helpful. In particular, Firefox usually eats too much memory and causes my computer to freeze. Earlyoom certainly helps with that.

However, when Firefox updated to v57 recently, it split out its tabs into sub-processes (similiar to Chrome). However, the main Firefox process often has the highest oom_score and is killed by earlyoom. For some reason, doing this orphans the sub-processes and causes a huge CPU spike---and usually a crash.

Everything works fine when a sub-processes is killed. So ideally, earlyoom would be able to selectively kill a tab's sub-process and not the entire Firefox process.

If you have any recommendations about how to accomplish this, I would really appreciate them. Otherwise, I found earlier comments by @joeytwiddle about implementing a "priority kill." So, I [forked](/TomJohnZ/earlyoom/tree/favor_unfavor_process) his code and modified it slightly. I've been testing it for a few days and it seems to do the job quite well. If you'd like---and if it's okay by @joeytwiddle ---I'd be happy to submit a PR.

**Comment by rfjakob** [comment]
Feature makes sense! I'll post a few comments on the code, but once a few details are ironed out I will merge this.

**Comment by TomJohnZ** [comment]
Ok, I've made the requested changes. Thanks for the recommendations!

I'm somewhat unfamiliar with C, so if you could briefly look over the latest commits, that'd be much appreciated. Everything seems to be working on my end.

If you have any other suggestions, I'd be happy to help. Otherwise, I can squash the commits and submit a PR.

**Comment by rfjakob** [comment]
Looks pretty good to me! Only two more nitpicks from me:

1) To **indent** use tabs (looks good now!), but to **align**, please use spaces. This makes the code look OK for any tab size (github seems to use 8).
![screenshot from 2018-01-23 09-09-09](https://user-images.githubusercontent.com/286847/35264479-3343fdd4-001d-11e8-89a3-75abf12c1da8.png)

2) To avoid future collisions with a "P" or "A" option, please use some value > 255.

```diff
+			case 'P':
+				prefer_cmds = optarg;
+				break;
+			case 'A':
+				avoid_cmds = optarg;
+				break;
```
I suggest something like EncFS does here: https://github.com/vgough/encfs/blob/master/encfs/main.cpp#L46
```
/* Arbitrary identifiers for long options that do
 * not have a short version */
#define LONG_OPT_ANNOTATE 513
#define LONG_OPT_NOCACHE 514
#define LONG_OPT_REQUIRE_MAC 515
```

**Comment by TomJohnZ** [comment]
Great, thanks for the suggestions! I've committed them to my branch. If there's anything else you see, please don't hesitate to let me know.

**Comment by rfjakob** [comment]
Looks good to merge - go ahead with the PR!
