### ISSUE TITLE
Can compile but running fails with: Could not find "MemAvailable:"

### ISSUE THREAD

**Issue by joeytwiddle** [rfjakob/earlyoom#5]
The new version compiles fine, but when I run it I get:

    $ ./earlyoom
    earlyoom v0.7-1-g131aa9c
    Could not find "MemAvailable:"

Any idea how I can fix this?

(gcc 4.6.3, libc 2.15 on Ubuntu 12.04)

**Comment by rfjakob** [comment]
Hm. You must running a kernel older than 3.14, so you don't have
MemAvailable.
I will re-add the old crude mechanism as a fallback for old kernels.

The new version compiles fine, but when I run it I get:

$ ./earlyoom
earlyoom v0.7-1-g131aa9c
Could not find "MemAvailable:"

Any idea how I can fix this?

(gcc 4.6.3, libc 2.15 on Ubuntu 12.04)

—
Reply to this email directly or view it on GitHub
<https://github.com/rfjakob/earlyoom/issues/5>.

**Comment by rfjakob** [comment]
Ok, I have added guesstimate code for that case. Pushed to master, would you like to test?

**Comment by joeytwiddle** [comment]
Just tested it. Works as expected. Thanks! :)
