### ISSUE TITLE
Set when to kill OOM when using `systemctl` (systemd)

### ISSUE THREAD

**Issue by diamondburned** [rfjakob/earlyoom#51]
Hey, just installed OOM, and I started earlyoom by doing `sudo systemctl enable earlyoom` and `sudo systemctl start earlyoom`. Where do I set the `-m` option for `earlyoom`?

Inside `earlyoom.service`: 

    ExecStart=/usr/local/bin/earlyoom $EARLYOOM_ARGS

Not sure where `$EARLYOOM_ARGS` is

**Comment by rfjakob** [comment]
If you are on Debian, this is defined in /etc/default/earlyoom . But you can also just write the options you want directly into earlyoom.service.
