### ISSUE TITLE
Never-Kill-RegEx

### ISSUE THREAD

**Issue by NicoWeio** [rfjakob/earlyoom#56]
_Last suggestion for today:_

While testing the script (setting the minimum RAM to ca. 95%) I noticed that it would even kill my desktop environment in order to free up some space. I guess there are more "realistic" cases where an option _Do not kill those processes, whatever happens_, would be useful, though. So how about adding this? :)

**Comment by hakavlad** [comment]
```
       --prefer REGEX
              prefer killing processes matching REGEX (adds 300 to oom_score)

       --avoid REGEX
              avoid killing processes matching REGEX (subtracts 300 from oom_score)
```
@rfjakob why add or subtracts 300? Why not 200 or 500?
Why do you use +/- instead of multiplication and division?

What is advantages of adding and subtracts?
What is disadvantages of multiplication and division?

**Comment by rfjakob** [comment]
1) Why +-: It's how things work in the Linux kernel with /proc/PID/oom_score_adj

2) The number 300 is arbitrary, but it is what [Chrome uses](https://bugs.chromium.org/p/chromium/issues/detail?id=333617), and it seems reasonable.

**Comment by hakavlad** [comment]
>but it is what Chrome uses, and it seems reasonable

For this case there is an option -i.

**Comment by rfjakob** [comment]
No I mean that the chrome people decided that "prefer killing this process" = 300. So I did the same.

**Comment by hakavlad** [comment]
Cool, thanks.

**Comment by rfjakob** [comment]
@NicoWeio I cannot see a realistic use case here. Modern distros protect ssh and things like that against the oom killer using `oom_score_adj`, but those processes are *tiny*. A process using more than 30% of memory should not be protected.
