### ISSUE TITLE
What is a good default memory/swap limit?

### ISSUE THREAD

**Issue by joeytwiddle** [rfjakob/earlyoom#6]
At various times I have tried 5%, 10% and 15%.  What have you guys found works for you?

I found on both my machines, I need to set the OOM killer to engage when I have 300 MB RAM and 300 MB swap remaining. This is the point when the swap starts thrashing.

(Although curiously on my machine with 8 GB RAM and 2 GB swap, if I **don't** run earlyoom, eventually I will end up with 600 MB RAM and 0 MB swap remaining, and at this point the system becomes unresponsive.)

I wonder if a fixed value of **300 MB RAM** and **300 MB swap** would satisfy most users.  (I don't see why someone with 16 GB RAM would need to engage the OOM killer earlier than someone with 8 GB RAM.)

But obviously on a small machine (e.g. with only 1Gig RAM), the 300MB threshold would be far too high!  So perhaps we should be using a percentage, with 300 as the upper limit...?

Interested to hear what values others are using.

**Comment by rfjakob** [comment]
I used to have 8 GB of RAM and now swap. Now that I have an SSD I have added 1 GB of swap. For both cases, 10% has worked fine in my opinion.

**Comment by joeytwiddle** [comment]
So I previously said that 300MB seems to be the minimum. I think 350-400MB is probably safer for a responsive system. Those figures came from a 32bit machine where I had only 2GB of RAM, so memory was quite precious to me.

But if you have lots of memory, and lots of processes that you don't really care that much about (in my case, hundreds of browser tabs), then setting a higher limit for the oom killer will preserve your **disk cache**. This might be desirable!

I actually found preserving my **disk cache** was more useful to me than preserving an extra 10 idle old browser tabs. Because retaining the disk cache keeps my system operating smooth and fast.

Because if you go down to the lowest limit (300MB) before invoking the oom killer, then the disk cache for your most commonly used programs and files (in my case my editor and its plugins) will be emptied. So next time you need those files, they will be fetched off the disk again.

Since I have 8GB RAM on this new laptop, I went and reserved a whole 1.2G of that for the disk cache, as an experiment.

The result of this is that my editor always opens quickly, and searching trees of source code files doesn't always become slow after the oom killer, because the data is still in memory!

So if you have lots of memory, I can recommend quite a large limit. But it's a personal preference, depending on how valuable your active windows are, and how you use your machine.

**Comment by rfjakob** [comment]
I guess that we agree means I can close the ticket :)
