### ISSUE TITLE
Low memory is not OOM

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#60]
> Out of memory (OOM) is an often undesired state of computer operation where **no additional memory can be allocated for use by programs or the operating system**. Such a system will be unable to load any additional programs, and since many programs may load additional data into memory during execution, these will cease to function correctly. This usually occurs because all available memory, including disk swap space, has been allocated.

In normal operation, earlyoom should not occur at all OOM, since preventing OOM is the main task of earlyoom, not a reaction to OOM that has already occurred.

What about replace "Out of memory!" in earlyoom stdout with "Preventing OOM!"?

**Comment by rfjakob** [comment]
It's right in the title

> The Early OOM Daemon

**Comment by hakavlad** [comment]
Earlyoom acts early OOM, but 10% MemAvailable is not OOM.

**Comment by hakavlad** [comment]
very good
