### ISSUE TITLE
Unexpected behavior: unknown version instead of 1.0

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#63]
subj

**Comment by rfjakob** [comment]
When / how do you get this? (Thanks for the report!)

**Comment by rfjakob** [comment]
The version only works if you clone the git repo (it uses git tags to find the version number). You downloaded the zip from https://github.com/rfjakob/earlyoom/releases/tag/v1.0 ?

**Comment by rfjakob** [comment]
Please try

    git clone https://github.com/rfjakob/earlyoom.git

**Comment by hakavlad** [comment]
Yes, I downloaded zip. I get it.

**Comment by rfjakob** [comment]
Ok!
