### ISSUE TITLE
How much memory does earlyoom use?

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#64]
1.8 MiB (Debian 9 x86_64)
2.0 MiB (Fedora 28)
2.2 MiB (Debian 8 i386, https://i.imgur.com/MaRPWwE.png)
Not about 0.6 MiB.

**Comment by rfjakob** [comment]
Hmm indeed. Has gotten bigger over time.
```
$ sudo grep VmRSS /proc/$(pgrep earlyoom)/status
VmRSS:	    2004 kB
```

**Comment by rfjakob** [comment]
Fixed via https://github.com/rfjakob/earlyoom/commit/124239d9c83a317ae98f4e739f95286df5c2ca70 , thanks for checking!
