### ISSUE TITLE
Wrong victim name

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#65]
I ran tail /dev/zero, and tail killed, but earlyoom 1.0 displays wrong name

mem avail: 0 MiB (0 %), swap free: 2425 MiB (41 %)
mem avail: 0 MiB (0 %), swap free: 1631 MiB (27 %)
mem avail: 0 MiB (0 %), swap free: 830 MiB (14 %)
Out of memory! avail: 0 MiB < min: 587 MiB
Killing process 1526 sudo
mem avail: 5057 MiB (86 %), swap free: 5564 MiB (94 %)
mem avail: 5196 MiB (88 %), swap free: 5566 MiB (94 %)

**Comment by hakavlad** [comment]
I ran tail again, earlyoom displays sudo again

mem avail: 0 MiB (0 %), swap free: 3007 MiB (51 %)
mem avail: 0 MiB (0 %), swap free: 2227 MiB (37 %)
mem avail: 0 MiB (0 %), swap free: 1404 MiB (23 %)
mem avail: 0 MiB (0 %), swap free: 670 MiB (11 %)
Out of memory! avail: 0 MiB < min: 587 MiB
Killing process 1760 sudo
mem avail: 5051 MiB (85 %), swap free: 4952 MiB (84 %)
mem avail: 5044 MiB (85 %), swap free: 4953 MiB (84 %)
mem avail: 5036 MiB (85 %), swap free: 4955 MiB (84 %)

**Comment by hakavlad** [comment]
I ran tail /dev/zero again, earlyoom displays sh. 
Pid is correct, but name is incorrect.

mem avail: 0 MiB (0 %), swap free: 4098 MiB (69 %)
mem avail: 0 MiB (0 %), swap free: 3354 MiB (57 %)
mem avail: 0 MiB (0 %), swap free: 2584 MiB (43 %)
mem avail: 0 MiB (0 %), swap free: 1779 MiB (30 %)
mem avail: 0 MiB (0 %), swap free: 1063 MiB (18 %)
Out of memory! avail: 0 MiB < min: 587 MiB
Killing process 1786 sh
mem avail: 129 MiB (2 %), swap free: 4112 MiB (69 %)
mem avail: 4824 MiB (82 %), swap free: 5058 MiB (86 %)
mem avail: 4818 MiB (82 %), swap free: 5059 MiB (86 %)
mem avail: 4811 MiB (81 %), swap free: 5062 MiB (86 %)

**Comment by hakavlad** [comment]
I ran `while true; do stress -m 6 --vm-bytes 10G; done`, earlyoom duisplays

mem avail: 4978 MiB (84 %), swap free: 5590 MiB (95 %)
mem avail: 4977 MiB (84 %), swap free: 5590 MiB (95 %)
mem avail: 1705 MiB (29 %), swap free: 5590 MiB (95 %)
mem avail: 0 MiB (0 %), swap free: 5267 MiB (89 %)
mem avail: 0 MiB (0 %), swap free: 4407 MiB (75 %)
mem avail: 0 MiB (0 %), swap free: 3445 MiB (58 %)
mem avail: 0 MiB (0 %), swap free: 2468 MiB (42 %)
mem avail: 0 MiB (0 %), swap free: 1517 MiB (25 %)
mem avail: 0 MiB (0 %), swap free: 570 MiB (9 %)
Out of memory! avail: 0 MiB < min: 587 MiB
Killing process 8230 sudo
mem avail: 732 MiB (12 %), swap free: 5243 MiB (89 %)
mem avail: 5181 MiB (88 %), swap free: 5503 MiB (93 %)
mem avail: 1763 MiB (30 %), swap free: 5505 MiB (93 %)
mem avail: 0 MiB (0 %), swap free: 5014 MiB (85 %)
mem avail: 0 MiB (0 %), swap free: 4074 MiB (69 %)
mem avail: 0 MiB (0 %), swap free: 3145 MiB (53 %)
mem avail: 0 MiB (0 %), swap free: 2201 MiB (37 %)
mem avail: 0 MiB (0 %), swap free: 1282 MiB (21 %)
Out of memory! avail: 0 MiB < min: 587 MiB
Killing process 8240 mate-notificati
mem avail: 0 MiB (0 %), swap free: 1153 MiB (19 %)
mem avail: 5180 MiB (88 %), swap free: 5492 MiB (93 %)
mem avail: 1592 MiB (27 %), swap free: 5493 MiB (93 %)
mem avail: 0 MiB (0 %), swap free: 5018 MiB (85 %)
mem avail: 0 MiB (0 %), swap free: 4091 MiB (69 %)
mem avail: 0 MiB (0 %), swap free: 3118 MiB (53 %)
mem avail: 0 MiB (0 %), swap free: 2136 MiB (36 %)
mem avail: 0 MiB (0 %), swap free: 1151 MiB (19 %)
Out of memory! avail: 0 MiB < min: 587 MiB
Killing process 8255 kworker/0:2
mem avail: 231 MiB (3 %), swap free: 1345 MiB (22 %)
mem avail: 4310 MiB (73 %), swap free: 5498 MiB (93 %)
mem avail: 0 MiB (0 %), swap free: 5496 MiB (93 %)
mem avail: 0 MiB (0 %), swap free: 4599 MiB (78 %)
mem avail: 0 MiB (0 %), swap free: 3656 MiB (62 %)
mem avail: 0 MiB (0 %), swap free: 2680 MiB (45 %)
mem avail: 0 MiB (0 %), swap free: 1720 MiB (29 %)
mem avail: 0 MiB (0 %), swap free: 753 MiB (12 %)
Out of memory! avail: 0 MiB < min: 587 MiB
Killing process 8263 notify-send
mem avail: 223 MiB (3 %), swap free: 3375 MiB (57 %)
mem avail: 2732 MiB (46 %), swap free: 5507 MiB (93 %)
mem avail: 0 MiB (0 %), swap free: 5230 MiB (89 %)
mem avail: 0 MiB (0 %), swap free: 4270 MiB (72 %)
mem avail: 0 MiB (0 %), swap free: 3323 MiB (56 %)
mem avail: 0 MiB (0 %), swap free: 2364 MiB (40 %)
mem avail: 0 MiB (0 %), swap free: 1384 MiB (23 %)
Out of memory! avail: 0 MiB < min: 587 MiB
Killing process 8276 stress
mem avail: 0 MiB (0 %), swap free: 721 MiB (12 %)
mem avail: 4021 MiB (68 %), swap free: 5503 MiB (93 %)
mem avail: 1081 MiB (18 %), swap free: 5503 MiB (93 %)
mem avail: 0 MiB (0 %), swap free: 4874 MiB (82 %)
mem avail: 0 MiB (0 %), swap free: 3939 MiB (67 %)
mem avail: 0 MiB (0 %), swap free: 2985 MiB (50 %)
mem avail: 0 MiB (0 %), swap free: 2025 MiB (34 %)
mem avail: 0 MiB (0 %), swap free: 1036 MiB (17 %)
Out of memory! avail: 0 MiB < min: 587 MiB
Killing process 8283 stress
mem avail: 77 MiB (1 %), swap free: 1261 MiB (21 %)
mem avail: 4299 MiB (73 %), swap free: 5497 MiB (93 %)
mem avail: 15 MiB (0 %), swap free: 5497 MiB (93 %)
mem avail: 0 MiB (0 %), swap free: 4617 MiB (78 %)
mem avail: 0 MiB (0 %), swap free: 3664 MiB (62 %)
mem avail: 0 MiB (0 %), swap free: 2744 MiB (46 %)
mem avail: 0 MiB (0 %), swap free: 1767 MiB (30 %)
mem avail: 0 MiB (0 %), swap free: 817 MiB (13 %)
Out of memory! avail: 0 MiB < min: 587 MiB
Killing process 8291 dbus-launch
mem avail: 383 MiB (6 %), swap free: 2372 MiB (40 %)
mem avail: 3401 MiB (57 %), swap free: 5506 MiB (93 %)
mem avail: 0 MiB (0 %), swap free: 5374 MiB (91 %)
mem avail: 0 MiB (0 %), swap free: 4408 MiB (75 %)
mem avail: 0 MiB (0 %), swap free: 3433 MiB (58 %)
mem avail: 0 MiB (0 %), swap free: 2485 MiB (42 %)
mem avail: 0 MiB (0 %), swap free: 1521 MiB (25 %)
mem avail: 0 MiB (0 %), swap free: 555 MiB (9 %)
Out of memory! avail: 0 MiB < min: 587 MiB
Killing process 8303 stress
mem avail: 379 MiB (6 %), swap free: 4765 MiB (81 %)
mem avail: 1981 MiB (33 %), swap free: 5501 MiB (93 %)
mem avail: 0 MiB (0 %), swap free: 5084 MiB (86 %)
mem avail: 0 MiB (0 %), swap free: 4178 MiB (71 %)
mem avail: 0 MiB (0 %), swap free: 3256 MiB (55 %)
mem avail: 0 MiB (0 %), swap free: 2280 MiB (38 %)
mem avail: 0 MiB (0 %), swap free: 1289 MiB (21 %)
Out of memory! avail: 0 MiB < min: 587 MiB
Killing process 8310 stress
mem avail: 0 MiB (0 %), swap free: 972 MiB (16 %)
mem avail: 4937 MiB (84 %), swap free: 5510 MiB (93 %)
mem avail: 613 MiB (10 %), swap free: 5510 MiB (93 %)
mem avail: 0 MiB (0 %), swap free: 4769 MiB (81 %)
mem avail: 0 MiB (0 %), swap free: 3802 MiB (64 %)
mem avail: 0 MiB (0 %), swap free: 2842 MiB (48 %)
mem avail: 0 MiB (0 %), swap free: 1853 MiB (31 %)
mem avail: 0 MiB (0 %), swap free: 854 MiB (14 %)
Out of memory! avail: 0 MiB < min: 587 MiB
fopen 8323/oom_score failed: No such file or directory
Killing process 8318 notify-send
mem avail: 361 MiB (6 %), swap free: 2389 MiB (40 %)
mem avail: 3325 MiB (56 %), swap free: 5490 MiB (93 %)
mem avail: 0 MiB (0 %), swap free: 5325 MiB (90 %)
mem avail: 0 MiB (0 %), swap free: 4386 MiB (74 %)
mem avail: 0 MiB (0 %), swap free: 3404 MiB (57 %)

**Comment by rfjakob** [comment]
Wow, interesting!

**Comment by hakavlad** [comment]
Distro is Debian 9 x86_64

**Comment by rfjakob** [comment]
Oh, looks like this has already been fixed some time ago in https://github.com/rfjakob/earlyoom/commit/7634c5b66dd7e9b88c6ebf0496c8777f3c4b3cc1 . Fix will be in v1.1.

**Comment by rfjakob** [comment]
Fix released in v1.1
