### ISSUE TITLE
Not informative output if swap enabled

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#66]
Out of memory! avail: 0 MiB < min: 587 MiB

One this line is not enaugh. Earlyoom not displays swap status info.

I want to see stdout like this:

mem avail: 0 MiB < min: 587 MiB
swap free: 500 MiB < min: 587 MiB
Preventing OOM: killing process...

**Comment by rfjakob** [comment]
It' actually two lines - the memory stats are printed one extra time before killing a process:

```
./earlyoom -r 0
earlyoom v1.1-5-g74a364b-dirty
mem total: 7836 MiB, min: 783 MiB (10 %)
swap total: 0 MiB, min: 0 MiB (10 %)

(silence)

mem avail: 712 MiB (9 %), swap free: 0 MiB (0 %)
Out of memory! mem min: 783 MiB, swap min: 0 MiB
Killing process: tail, pid: 5476, badness: 367, VmRSS: 719 MiB
```

But I agree that the output could be nicer. Fixing https://github.com/rfjakob/earlyoom/issues/62 will need some changes there, anyway, and I'll see if I can get nicer kill output as well.

**Comment by hakavlad** [comment]
OK, thanks.
