### ISSUE TITLE
What about SIGTERM?

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#67]
2018 will end soon, but the signal is still not supported.

**Comment by hakavlad** [comment]
I expect follow behavior by default: 10% - SIGTERM, 5% - SIGKILL.

**Comment by rfjakob** [comment]
Do you know an app that does something useful on SIGTERM?

**Comment by hakavlad** [comment]
I did not understand what you meant.
I know that most of apps accept SIGTERM and terminate correctly.

**Comment by hakavlad** [comment]
It happens quickly in most cases. Even it will need additional memory, process will killed at 5%. Also, user will can set thresholds like that: 10% SIGKILL and 0% SIGTERM for ignore SIGTERM. 
SIGTERM used in [full-featured OOM preventer](https://github.com/hakavlad/nohang), and no any problem happens.

**Comment by rfjakob** [comment]
The thing is, this is an extra option that the user may have to think about.

earlyoom only uses sigkill and works fine!

**Comment by hakavlad** [comment]
> extra option that the user may have to think about

I think that users are not idiots.

**Comment by rfjakob** [comment]
> Should I stop offer any features more?

No, don't stop! I like several of them.

**Comment by rfjakob** [comment]
I am cleaning up old tickets and

**Comment by rfjakob** [comment]
I am going through old tickets, and read this https://github.com/rfjakob/earlyoom/issues/34 again. 

Apparently postgresql does something useful on SIGTERM. I'll think again about this.
