### ISSUE TITLE
Sleep 10 causes earlyoom not prevents OOM

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#68]
I ran `while true; do tail /dev/zero; done`, and eventually Xorg has been killed because earlyoom slept.

**Comment by hakavlad** [comment]
I decide the problem with multiple killing like this: sleep 0.5 after any SIGTERM and sleep 3 after any SIGKILL in nohang by default (it can be changed with a config), and problem not happens. Also, there is min_badness in config as another way to prevent killing innocent victims.

**Comment by hakavlad** [comment]
Problem happens if 2 earlyooms started.

**Comment by rfjakob** [comment]
Sounds like it works as intended.

The `sleep(10)` is to prevent spamming the log and killing innocent processes (because the PID can be reused by a different process).
