### ISSUE TITLE
Reduce badness of certain processes using regexp

### ISSUE THREAD

**Issue by joeytwiddle** [rfjakob/earlyoom#7]
I found earlyoom was too often killing the main firefox process, or the main chrome process, when I would really rather it had killed just one or two of the chrome tabs I had open, instead of killing a whole browser session!

My approach to this has been to reduce the badness of processes matching a certain regexp.  I compare the regexp against the process cmdline, rather than just the process name, so that I can be kind to the main process, but not to tabs or extensions.  (I divide badness by 32.)

My fork based on your older code is here: https://github.com/joeytwiddle/earlyoom/tree/logging_usleep

It has been working for me, and I found it very useful (so that I don't lose my whole browser when I have 100 tabs open).  I hope you also like the idea, and will consider merging it in!  (I could create a PR.)

Here is a more up-to-date version which is merged with your `oom_adj` code (which is kind of overkill!): https://github.com/joeytwiddle/earlyoom

However now I am interested in reducing the badness of recently-created or running processes.  (Because I would prefer if earlyoom attacks chrome tabs I haven't used for a long time, rather than tabs I am using right now.)  (I suspect recently started processes are much easier to detect in Linux than recently used...  ;) )  That's now in #8

**Comment by rfjakob** [comment]
v0.7 takes oom_score_adj into account by default (disable with -i).
This will make the chrome renderer tabs die long before the main process.
I think using oom_score_adj is the right thing to do to express what you
want to have killed, as it will also take affect under a real kernel oom.

**Comment by rfjakob** [comment]
I understand that you cant test v0.7 right now, will fix that one soon ;)

**Comment by joeytwiddle** [comment]
That is interesting. I must read about oom_score_adj. Perhaps my hack will not be needed! Cheers. :)

**Comment by rfjakob** [comment]
The kernel itself actually has very good documentation about oom_score_adj. It is in https://www.kernel.org/doc/Documentation/filesystems/proc.txt , I am quoting the key part below:

    The value of /proc/<pid>/oom_score_adj is added to the badness score before it
    is used to determine which task to kill.  Acceptable values range from -1000
    (OOM_SCORE_ADJ_MIN) to +1000 (OOM_SCORE_ADJ_MAX).  This allows userspace to
    polarize the preference for oom killing either by always preferring a certain
    task or completely disabling it.  The lowest possible value, -1000, is
    equivalent to disabling oom killing entirely for that task since it will always
    report a badness score of 0.

    Consequently, it is very simple for userspace to define the amount of memory to
    consider for each task.  Setting a /proc/<pid>/oom_score_adj value of +500, for
    example, is roughly equivalent to allowing the remainder of tasks sharing the
    same system, cpuset, mempolicy, or memory controller resources to use at least
    50% more memory.  A value of -500, on the other hand, would be roughly
    equivalent to discounting 50% of the task's allowed memory from being considered
    as scoring against the task.

**Comment by joeytwiddle** [comment]
Thanks for that. It's good to use the preexisting score adjustment, although I would need some way to set the value for processes which don't already set their own (e.g. a shellscript wrapper for Firefox).

These days I am having another problem, which I will add in a new issue.

For anyone interested in seeing what oom_adj scores their system is currently using, here is a script I wrote.  (I called it `list_oomadjusted_processes.sh`)

    #!/bin/sh
    
    oom_what=oom_adj
    #oom_what=oom_score_adj
    #oom_what=oom_score
    
    [ -z "$COLUMNS" ] && COLUMNS=`tput cols`
    
    grep -v '^0$' /proc/*/$oom_what |
    cut -d / -f 3 |
    sort -n |
    while read proc
    do
        oom_adj=`cat /proc/$proc/$oom_what`
        cmdline=`cat /proc/$proc/cmdline`
        echo "$proc $oom_adj $cmdline"
    done |
    sort -n -k 2 |
    cut -c 1-$COLUMNS

**Comment by hakavlad** [comment]
@joeytwiddle 

>when I would really rather it had killed just one or two of the chrome tabs

Best solution is matching with cmdline.

For example, in nohang, use follow config for chromium tabs:
```
@CMDLINE_RE 400 /// --type=renderer
```

It allows to prevent killing chromium parent process and prefer chromium tabs.

https://github.com/hakavlad/nohang/blob/master/nohang.conf

Maybe cmdline matching will appear in earlyoom.
