### ISSUE TITLE
Notify-send slowdown

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#73]
...if `&` not in the end of the command.

Replace
`"-i dialog-warning 'earlyoom' 'Killing process %d %s'", victim_pid, victim_name);`
with
`"-i dialog-warning 'earlyoom' 'Killing process %d %s' &", victim_pid, victim_name);`
will fix the problem

**Comment by hakavlad** [comment]
Earlyoom slowdowns until notify-send runs. Adding '&' fixes problem.

**Comment by rfjakob** [comment]
I see. But we also have to stop sending notifications until the first one is finished.

**Comment by rfjakob** [comment]
Otherwise we may spawn too many processes, and slow the system down even worse.

**Comment by hakavlad** [comment]
>  spawn too many processes, and slow the system down even worse

Have you seen this in fact even once?

**Comment by hakavlad** [comment]
Slowdown the system will stop after 1st SIGKILL.

**Comment by rfjakob** [comment]
Yes i have seen this with cronjobs that pile up. The server then enters a death spiral

**Comment by rfjakob** [comment]
earlyoom was sending the notification first, and kills later. As sending the notification needs memory, this was stupid. The change https://github.com/rfjakob/earlyoom/commit/b2fe57ca23d4c461c40fc7fc61ace8d2dbada1d5 kills first, and notifies later. Does this fix the slowdown you see?

**Comment by hakavlad** [comment]
I need test it, I try it later.

**Comment by rfjakob** [comment]
PS: https://github.com/rfjakob/earlyoom/commit/c91dc9e536b41644d447bc66a76873c0716fbd9c

**Comment by hakavlad** [comment]
Thank you very much

**Comment by hakavlad** [comment]
>kills first, and notifies later. Does this fix the slowdown you see?

Works great, thanks!

**Comment by rfjakob** [comment]
Thanks for testing!

**Comment by hakavlad** [comment]
@rfjakob 

>Otherwise we may spawn too many processes, and slow the system down even worse.

I ran even 
```
while true; do (notify-send lol &); done
```
and nothing happened.
Notify-send is very short-life process,  it just quickly send info to notification daemon and die.
That's why using Popen and & seems like not dangerous.

**Comment by rfjakob** [comment]
That contradicts what you saw in https://github.com/rfjakob/earlyoom/issues/73#issuecomment-403103009 , right?
