### ISSUE TITLE
Sanitize process name for GUI notification helper

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#76]
Is it not enough to drop out only ', ", backslash and backtick? Why do you drop out all Unicode?

**Comment by rfjakob** [comment]
Hmm. Maybe it is enough to do what you say, actually. Within single quotes, `$( )` and newlines should do no harm.

But look at `php_escape_shell_arg()`:
https://github.com/php/php-src/blob/5eb1f92f31cafc48384f9096012f421b37f6d425/ext/standard/exec.c#L393

It's huge and scary, and I'd rather have somewhat garbled process names in the GUI notification than adding a function like this.

**Comment by hakavlad** [comment]
I want to use 
```
name.strip('\'"`\\!-$')
```

**Comment by hakavlad** [comment]
PS.  News: earlyoom 1.1 release http://www.opennet.ru/opennews/art.shtml?num=48927
Users in comments are happy!

**Comment by rfjakob** [comment]
I think with Python you could use `subprocess.run(..., shell=false)`. This shoud avoid the shell completely, and you don't have to escape anything.

In C I could use `execv()`.  I have thought about switchig to execv(), it's a better solution.
But it would have required more code changes, so I chose the "simple and safe" solution for a quick fix.

Switching to execv is planned for the future.

**Comment by hakavlad** [comment]
Ok, thanks. But subprocess needs additional import and +mem usage.

**Comment by rfjakob** [comment]
I think I'll keep this as it is now. Too dangerous, and too hard to get right.
