### ISSUE TITLE
Not killing processes

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#79]
https://github.com/rfjakob/earlyoom/issues/78
IMO it was unexpected behavior. 

What happens if start earlyoom -m 50?
Is it true that the swap is then not counted at all?

**Comment by rfjakob** [comment]
The default is: 10% memory, 10% swap.
If you use -m 50, you have 50% memory, 10% swap.

**Comment by rfjakob** [comment]
It will kill a process when memory is below 50% AND swap is below 10%.

**Comment by hakavlad** [comment]
Such OK, very expected!

**Comment by mark2185** [comment]
@hakavlad It was unexpected, but it **is** stated in the readme, **twice**.
