### ISSUE TITLE
-i

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#81]
The documentation does not explain how this option works.
Could you tell us how this option works?
Is it true that it just subtracts 300 from oom_score?

**Comment by rfjakob** [comment]
It's like this:

"kernel badness" = some value that the kernel calculates from process memory usage. This is not visible in /proc.

`/proc/[pid]/oom_score` = badness + `/proc/[pid]/oom_score_adj`

Usually, the value earlyoom looks at is oom_score:

"earlyoom badness" = `oom_score`

With -i, we undo the effect of `oom_score_adj`:

"earlyoom badness" = `oom_score` - `oom_score_adj`

**Comment by hakavlad** [comment]
Cool, thanks.
