### ISSUE TITLE
overcommit and cgroups

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#82]
I think that overcommit=2 and cgroups should be mentioned in README as alternative ways to prevent OOM. And their advantages and disadvantages should be declared.

**Comment by hakavlad** [comment]
Also see https://www.reddit.com/r/linux/comments/56r4xj/why_are_low_memory_conditions_handled_so_badly/

**Comment by hakavlad** [comment]
I am not tested cgroups and have not any idea right now. I will test it in future, maybe.

**Comment by rfjakob** [comment]
Ok. I am open for better docs, but I'll close this for now.

**Comment by hakavlad** [comment]
See also https://www.reddit.com/r/linux/comments/aqd9mh/memory_management_more_effective_on_windows_than/

**Comment by JohnAZoidberg** [comment]
> systemd-run --scope -p MemoryMax=2G firefox

That just leads to Firefox getting killed all of the time...
We need a way to make Firefox use less memory.

**Comment by hakavlad** [comment]
>make Firefox use less memory

dom.ipc.processCount=1, uBlock Origin
