### ISSUE TITLE
Decrease CPU usage again, let change rate with CLI option

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#83]
0.5% CPU usage: https://i.imgur.com/6TrjyyS.png
Earlyoom is still not good enough for embedded because it does not allow to reduce the frequency of memory checking. 0.5 % CPU usage and very intensive monitoring may simply be redundant in some cases.

**Comment by hakavlad** [comment]
And could you add displaying sleep time in debug mode?

**Comment by rfjakob** [comment]
Sleep time is already displayed with -d

**Comment by hakavlad** [comment]
ok

**Comment by rfjakob** [comment]
How are your C skills, by the way?

**Comment by hakavlad** [comment]
I did not study С, and studied the python a little. It's all. I'm not a programmer.

**Comment by hakavlad** [comment]
How about adding response time in -d mode?
Like this:
```
* MemAvailable (342 MiB, 5.8 %) < mem_min_sigkill (353 MiB, 6.0 %)
  SwapFree (0 MiB, 0.0 %) < swap_min_sigkill (0 MiB, - %)
  Preventing OOM: trying to send the SIGKILL signal to stress,
  Pid: 9841, Badness: 87, VmRSS: 513 MiB, VmSwap: 0 MiB
  Success; response time: 11 ms
```
This is the time between the detection of threshold excess and the sending of a signal.

**Comment by rfjakob** [comment]
Yes, good idea

**Comment by rfjakob** [comment]
What kind of system is this? Can you run membomb so we see the memory fill speed?

**Comment by hakavlad** [comment]
>What kind of system is this?

What did you mean?

>Can you run membomb so we see the memory fill speed?

Yes, I can. Wait plaese

**Comment by rfjakob** [comment]
Is it a raspberry?

**Comment by hakavlad** [comment]
Ah, it is Debian 8 i386 on VirtualBox. Did you mean the system in the picture?

**Comment by rfjakob** [comment]
Yes the system where htop in the screenshot runs. Ok virtualbox, thanks.

**Comment by hakavlad** [comment]
>Can you run membomb so we see the memory fill speed?

http://okturing.com/src/4740/body

**Comment by hakavlad** [comment]
Why is sleep time limited to one second? What are the advantages?

**Comment by hakavlad** [comment]
Адаптивный алгоритм гарантирует хорошую реакцию. Зачем ограничивать время сна?

**Comment by rfjakob** [comment]
I have added the latency printout:

    selecting victim and sending signal took 11.852 ms

Your Python code seems pretty fast!

**Comment by rfjakob** [comment]
I just started earlyoom in a Debian 64bit VM, and the CPU usage consistently shows up as 0.0%:

![screenshot from 2018-07-21 20-31-33](https://user-images.githubusercontent.com/286847/43039050-16445d9c-8d25-11e8-98b9-0ec432cd116b.png)

I think 1 second intervals are good enough.

**Comment by rfjakob** [comment]
PS: This is what membomb inside the VM looks like:
```
$ ./membomb 
  39 MiB (1493 MiB/s)
  78 MiB (1453 MiB/s)
 117 MiB (1494 MiB/s)
 156 MiB (1281 MiB/s)
Killed
```
Your VM only got 100 MB/s. I think there is something wrong with your VM setup.

**Comment by hakavlad** [comment]
@rfjakob 
Maybe my processor does not support hardware acceleration.

**Comment by rfjakob** [comment]
I think you can find out with
```
egrep '^flags.*(vmx|svm)' /proc/cpuinfo
```
if you don't get output, the CPU does not support HW acceleration.

In this case I recommend to use VirtualBox, which works fast without HW accel, because it supports paravirtualization.

**Comment by hakavlad** [comment]
@rfjakob thank you.

>does not support HW acceleration

That's why I don't use KVM.

But 100 M/s I got in VirtualBox.

**Comment by rfjakob** [comment]
Strange, because your CPU is fast, as you get [high numbers](https://github.com/rfjakob/earlyoom/issues/61#issuecomment-403634836) if you run membomb on the host

**Comment by hakavlad** [comment]
@rfjakob 

>Your Python code seems pretty fast!

No!
in same cases:
nohang: 13 ms
earlyoom: 7 ms
