### ISSUE TITLE
Make install fails if Pandoc is missing

### ISSUE THREAD

**Issue by sgrimm-sg** [rfjakob/earlyoom#85]
If you run `make install` in an environment without Pandoc, the Makefile skips generating `earlyoom.1` but still tries to install it, which causes the build to fail.

**Comment by rfjakob** [comment]
Thanks for the report! Fixed by https://github.com/rfjakob/earlyoom/commit/c58b5813e0cb666815b7a836e98c49df3974ce82 . "make install" will work, but you won't have the man page, obviously.
