### ISSUE TITLE
No messages, chromium tabs don't get killed

### ISSUE THREAD

**Issue by megastallman** [rfjakob/earlyoom#86]
Hi @rfjakob !

Currently I'm trying to use the earlyoom killer. It looks simple and promising.
So I'm running $ ./earlyoom -n
on my Kubuntu, opening more chromium tabs, getting 8-7-6 % of free ram. But no notification occurs and no process is getting killed. Looks like I'm doing it wrong...

Thanks!

**Comment by megastallman** [comment]
~/Software/earlyoom$ ./earlyoom -n
earlyoom v1.1-36-g70b08f3
mem  total: 3828 MiB, min: 10 %
swap total: 4095 MiB, min: 10 %
notifications enabled using command: notify-send
mem avail:  357 of 3828 MiB ( 9 %), swap free: 3163 of 4095 MiB (77 %)
mem avail:  356 of 3828 MiB ( 9 %), swap free: 3163 of 4095 MiB (77 %)
mem avail:  356 of 3828 MiB ( 9 %), swap free: 3163 of 4095 MiB (77 %)
mem avail:  355 of 3828 MiB ( 9 %), swap free: 3163 of 4095 MiB (77 %)
mem avail:  355 of 3828 MiB ( 9 %), swap free: 3163 of 4095 MiB (77 %)
^C

**Comment by rfjakob** [comment]
You still have lots of free swap. Killing starts when both ram and swap are below 10%.

You can use `-s 100` if you want to ignore swap.
