### ISSUE TITLE
debug bug

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#89]
pid 32229: badness   1 vm_rss  10120 bash
pid 32236: badness 777 vm_rss 4666772 tail
    ^ new victim (higher badness)
Killing process 'tail' with signal 15, pid: 32236, badness: 777, VmRSS: 4557 MiB
selecting victim and sending signal took **-991.-688** ms
adaptive sleep time: 100 ms
adaptive sleep time: 254 ms
adaptive sleep time: 753 ms

![2018-07-26 04-53-55](https://user-images.githubusercontent.com/26821601/43224057-02946c10-9090-11e8-9da0-de19f1e61c4f.png)

**Comment by rfjakob** [comment]
Wow the value is complete garbage if the time is over 1 second. Fixed in https://github.com/rfjakob/earlyoom/commit/9822714c3ce404a1cbc475bd621e9a8f03f78911 , thanks!
