### ISSUE TITLE
Could not set oom_score_adj

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#90]
$ sudo earlyoom -p
earlyoom v1.1-44-g9822714
**Could not set oom_score_adj**: Success.  Continuing anyway
mem total: 999 MiB, sending sigterm at 10 %, sigkill at 5 %
swap total: 974 MiB, sending sigterm at 10 %, sigkill at 5 %
mem avail: 750 of 999 MiB (75 %), swap free: 577 of 974 MiB (59 %)
mem avail: 749 of 999 MiB (74 %), swap free: 578 of 974 MiB (59 %)

What does it mean? Is it OK?

**Comment by rfjakob** [comment]
Fixed, thanks!

**Comment by rfjakob** [comment]
The message is wrong, everything has worked.
