### ISSUE TITLE
earlyoom as a daemon on ubuntu 14.04

### ISSUE THREAD

**Issue by pavs** [rfjakob/earlyoom#91]
I am earlyoom on ubuntu 14.04.
It has helped me with my apache processes which were going out of control with memory usage and has stable so far. I have installed it from source but unfortunately there is no systemctl on 14.04 so I don't know how to run it as a daemon and always running in the back ground.

I am currently using by logging to my server by ssh and running it as a background process using screen. I would like to run it as a process all the time in the background - is crontab the ideal way to go?

**Comment by hakavlad** [comment]
# nohup earlyoom &
or
# nohup earlyoom > foo.out 2> foo.err < /dev/null &
simplest way
see https://en.wikipedia.org/wiki/Nohup

**Comment by hakavlad** [comment]
>is crontab the ideal way to go

not bad:
sudo crontab -e 
@reboot yourcommand
sudo service cron restart

**Comment by pavs** [comment]
Thanks for the tip, will try it out.

**Comment by joeytwiddle** [comment]
@pavs For a pre-systemd system, you might want to try `sudo make install-iniscript` instead of `sudo make install`

After that earlyoom should be added to the startup process.

You can edit the config file in `/etc/default/earlyoom` and restart it using `/etc/init.d/earlyoom restart`

**Comment by pavs** [comment]
@joeytwiddle Thanks for the great team!
