### ISSUE TITLE
Incomplete notification message

### ISSUE THREAD

**Issue by barsan-ds** [rfjakob/earlyoom#92]
Fore some reason the notification message is too short and does not contain the whole name of the process it kills. (Kubuntu 18.04, using libnotify-bin)
`Killing process 3977 TreeIterationTe`
instead of
`Killing process 3977 TreeIterationTest`
Plus some more explanations should be inserted. Imagine someone gets its hands one on some pc having this utility installed. At some point he sees the application he uses disappear with the message Killing process...
Some extra explanations could reduce the overall amount of WTF.

**Comment by hakavlad** [comment]
The process name can not contain more than 15 characters in /proc/<pid>/status,
it can't be fixed

**Comment by hakavlad** [comment]
>Some extra explanations

I agree, notification should be like

_Low memory!
Earlyoom prevents OOM, killing process ..._

**Comment by rfjakob** [comment]
Unfortunately there is no easy fix for the 15 characters limit, but I added a little more info to the notification in https://github.com/rfjakob/earlyoom/commit/9a36cd0dd083f08641b7ded244a53a6370bb2523 . Thanks for the report!
