### ISSUE TITLE
Custom swap and memory values are lost after shutdown

### ISSUE THREAD

**Issue by sianhulo** [rfjakob/earlyoom#94]
if one changes the 10% memory and or swap settings, the changes will be lost after shooting down computer. Any way to make these changes persistent?

**Comment by rfjakob** [comment]
Hi! How do you start earlyoom?

**Comment by sianhulo** [comment]
I had the systemd service enabled. But i noticed upon reboot that when my system got to be with under 5% of ram that earlyoom didn't run. Running it directly on console gave me to know that it had reverted back to the default values of 10% for memory and swap. so after changing my swap value to something higher it immediately freed space.

If it matters, I'm using the AUR version.

**Comment by rfjakob** [comment]
Can you post the output of

journalctl -b -u earlyoom

?

**Comment by sianhulo** [comment]
`-- Logs begin at Wed 2018-09-26 23:43:34 -04, end at Tue 2018-10-09 10:30:14 -04. --
oct 09 10:25:43 Deep-Blue systemd[1]: Started Early OOM Daemon.
oct 09 10:25:43 Deep-Blue earlyoom[388]: earlyoom 1.1
oct 09 10:25:43 Deep-Blue earlyoom[388]: mem total: 7966 MiB, min: 796 MiB (10 %)
oct 09 10:25:43 Deep-Blue earlyoom[388]: swap total: 7720 MiB, min: 772 MiB (10 %)`

Not seeing anything out of the ordinary.

**Comment by sianhulo** [comment]
ok, so I think the following is happening. The systemd service starts with default parameters, these are overwritten WHILE we run earlyoom directly on terminal with our own parameters  but they revert back when we close the process running on the terminal.

**Comment by sianhulo** [comment]
I checked the content of the systemd service and got to know of the existence of `$EARLYOOM_ARGS` and /etc/default/earlyoom, which is where one needs to get permanent changes.

Working fine now.
