### ISSUE TITLE
Add hint about configuration file to documentation

### ISSUE THREAD

**Issue by M4he** [rfjakob/earlyoom#95]
First of all, many thanks for creating this daemon! Finally no more desktop freezing in low mem situations.

I think you should add a little "Configuration" subsection to the README, hinting at the configuration file in `/etc/default/`. It's not obvious for people not deeply familiar with systemd.

From reading the README, at first I thought it only supported the CLI params and I had to hack the main systemd unit file to adjust it. When I opened it up I spotted the environment variable, which hinted at some kind of configurability and made me search for the corresponding file.

**Comment by rfjakob** [comment]
Hi! Good idea! Do you maybe want to start writing the section? You can just start editing here https://github.com/rfjakob/earlyoom/edit/master/README.md , and I will merge it once ready.
