### ISSUE TITLE
AUR helper

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#99]
https://wiki.archlinux.org/index.php/AUR_helpers

yaourt is stalled
maybe need fix readme

**Comment by rfjakob** [comment]
So there seems to be an AUR package already: https://aur.archlinux.org/packages/earlyoom/

What is the problem with the readme?

**Comment by rfjakob** [comment]
And the AUR package seems active:

> Last Updated:  2018-11-04 20:56

Looks ok to me?

**Comment by hakavlad** [comment]
>For Debian and Ubuntu, there's a Debian package:

It not works on Ubuntu 16.04 and Debian 9. I suggest the following:

For Debian 10+ and Ubuntu 18.04+, there's a Debian package:
```
sudo apt install earlyoom
```

For Arch Linux, there's an AUR package. Use your favorite AUR helper. For example,
```
sudo yaourt -S earlyoom
sudo systemctl enable earlyoom
sudo systemctl start earlyoom
```

**Comment by hakavlad** [comment]
>AUR package seems active

https://github.com/archlinuxfr/yaourt/commits/master
Commits on Mar 18, 2018 

https://aur.archlinux.org/packages/yaourt/
Last Updated: | 2017-07-19 20:22

https://aur.archlinux.org/packages/yaourt-git/
Last Updated: | 2016-03-20 16:37

**Comment by hakavlad** [comment]
https://i.imgur.com/xTqz4Hg.png

**Comment by rfjakob** [comment]
Oh, I see. What do people use nowadays?

**Comment by hakavlad** [comment]
pikaur, yay, trizen and other - https://wiki.archlinux.org/index.php/AUR_helpers#Pacman_wrappers

https://www.ostechnix.com/kill-largest-process-unresponsive-linux-system/ recommends `yay`

**Comment by rfjakob** [comment]
Text modified as suggested: https://github.com/rfjakob/earlyoom/commit/0e7c009a787a028984946f245ee3c7dc29eaf3de

Thanks
